

-- UNION E UNION ALL

SELECT NM_CLIENTE, DS_EMAIL FROM TB_CLIENTE
WHERE ID_CLIENTE < 10
UNION -- RETIRA OS DUPLICADOS "DISTINCT"
SELECT NM_CLIENTE, DS_EMAIL FROM TB_CLIENTE
WHERE ID_CLIENTE IN (8,9,10,11)

SELECT NM_CLIENTE, DS_EMAIL FROM TB_CLIENTE
WHERE ID_CLIENTE < 10
UNION ALL -- MANTEM OS DUPLICADOS "DISTINCT"
SELECT NM_CLIENTE, DS_EMAIL FROM TB_CLIENTE
WHERE ID_CLIENTE IN (8,9,10,11)

-- UNION E UNION ALL ORDENAÇÃO
SELECT NM_CLIENTE, DS_EMAIL FROM TB_CLIENTE
WHERE ID_CLIENTE < 10
UNION ALL -- MANTEM OS DUPLICADOS "DISTINCT"
SELECT NM_CLIENTE, DS_EMAIL FROM TB_CLIENTE
WHERE ID_CLIENTE IN (8,9,10,11)

ORDER BY NM_CLIENTE -- ORDENAR DEPOIS DA UNIAO

SELECT NM_CLIENTE, DS_EMAIL 
INTO #CLIENTE_PARTE1
FROM TB_CLIENTE
WHERE ID_CLIENTE < 10
ORDER BY ID_CLIENTE

SELECT NM_CLIENTE, DS_EMAIL 
INTO #CLIENTE_PARTE2
FROM TB_CLIENTE
WHERE ID_CLIENTE IN (8,9,10,11)
ORDER BY NM_CLIENTE

SELECT * FROM #CLIENTE_PARTE1
UNION ALL
SELECT * FROM #CLIENTE_PARTE2

-- EXCEPT E INTERSECT

-- CLIENTES QUE COMPRARAM EM JAN/21 E VOLTARAM A COMPRAR EM FEV/21
-- CLIENTES QUE COMPRARAM EM JAN/21
SELECT 
	TB_CLIENTE.ID_CLIENTE,
	TB_CLIENTE.NM_CLIENTE
FROM TB_CLIENTE
	INNER JOIN TB_VENDA 
		ON TB_CLIENTE.ID_CLIENTE = TB_VENDA.ID_CLIENTE
WHERE TB_VENDA.DT_VENDA BETWEEN '20210101' AND '20210131 23:59:59'
INTERSECT
-- CLIENTES QUE COMPRARAM EM FEV/21
SELECT 
	TB_CLIENTE.ID_CLIENTE,
	TB_CLIENTE.NM_CLIENTE
FROM TB_CLIENTE
	INNER JOIN TB_VENDA 
		ON TB_CLIENTE.ID_CLIENTE = TB_VENDA.ID_CLIENTE
WHERE TB_VENDA.DT_VENDA BETWEEN '20210201' AND '20210228 23:59:59'

SELECT 
	TB_CLIENTE.ID_CLIENTE,
	TB_CLIENTE.NM_CLIENTE
FROM TB_CLIENTE
	INNER JOIN TB_VENDA 
		ON TB_CLIENTE.ID_CLIENTE = TB_VENDA.ID_CLIENTE
WHERE TB_VENDA.DT_VENDA BETWEEN '20210101' AND '20210228 23:59:59'
GROUP BY TB_CLIENTE.ID_CLIENTE,	TB_CLIENTE.NM_CLIENTE
HAVING COUNT(DISTINCT MONTH(DT_VENDA)) = 2

-- CLIENTES QUE COMPRARAM EM JAN/21, MAS NÃO COMPRARAM EM FEV/21
-- CLIENTES QUE COMPRARAM EM JAN/21
SELECT 
	TB_CLIENTE.ID_CLIENTE,
	TB_CLIENTE.NM_CLIENTE
FROM TB_CLIENTE
	INNER JOIN TB_VENDA 
		ON TB_CLIENTE.ID_CLIENTE = TB_VENDA.ID_CLIENTE
WHERE TB_VENDA.DT_VENDA BETWEEN '20210101' AND '20210131 23:59:59'
EXCEPT
-- CLIENTES QUE COMPRARAM EM FEV/21
SELECT 
	TB_CLIENTE.ID_CLIENTE,
	TB_CLIENTE.NM_CLIENTE
FROM TB_CLIENTE
	INNER JOIN TB_VENDA 
		ON TB_CLIENTE.ID_CLIENTE = TB_VENDA.ID_CLIENTE
WHERE TB_VENDA.DT_VENDA BETWEEN '20210201' AND '20210228 23:59:59'

-- CLIENTES QUE COMPRARAM EM FEV/21, MAS NÃO COMPRARAM EM JAN/21

-- CLIENTES QUE COMPRARAM EM FEV/21
SELECT 
	TB_CLIENTE.ID_CLIENTE,
	TB_CLIENTE.NM_CLIENTE
FROM TB_CLIENTE
	INNER JOIN TB_VENDA 
		ON TB_CLIENTE.ID_CLIENTE = TB_VENDA.ID_CLIENTE
WHERE TB_VENDA.DT_VENDA BETWEEN '20210201' AND '20210228 23:59:59'

EXCEPT

-- CLIENTES QUE COMPRARAM EM JAN/21
SELECT 
	TB_CLIENTE.ID_CLIENTE,
	TB_CLIENTE.NM_CLIENTE
FROM TB_CLIENTE
	INNER JOIN TB_VENDA 
		ON TB_CLIENTE.ID_CLIENTE = TB_VENDA.ID_CLIENTE
WHERE TB_VENDA.DT_VENDA BETWEEN '20210101' AND '20210131 23:59:59'