USE DB_MADA_VAREJO

SELECT 
	name ,
	size/128.0														TAMANHO_ARQUIVO_MB,
	CAST(FILEPROPERTY(name, 'SpaceUsed') AS int)/128.0				ESPACO_UTILIZADO_MB,
	size/128.0- CAST(FILEPROPERTY(name, 'SpaceUsed') AS int)/128.0	ESPACO_DISPONIVEL_MB
FROM sys.database_files;

DBCC SHRINKDATABASE ( DB_MADA_VAREJO, TRUNCATEONLY)

-- INDICES
CREATE NONCLUSTERED INDEX IX_TB_VENDAITEM_ID_PRODUTO
ON [dbo].[TB_VENDAITEM] ([ID_PRODUTO])


-- TRANSA합ES

BEGIN TRAN -- BEGIN TRANSACTION "ABRE" A TRANSA플O

UPDATE TB_VENDA
SET VL_FRETE = 0 

-- FINALIZANDO A TRANSA플O
ROLLBACK -- VOLTA O BANCO AO ESTADO ANTERIOR A TRANSA플O

--
BEGIN TRAN

UPDATE TB_VENDA
SET VL_FRETE = 0 
WHERE ID_VENDA = (SELECT MAX(ID_VENDA) FROM TB_VENDA)

SELECT * FROM TB_VENDA ORDER BY ID_VENDA DESC

COMMIT  -- FINALIZA A TRANSA플O CONFIRMANDO AS A합ES