-- CLAUSULA OVER
SELECT * FROM TB_PRODUTO

SELECT AVG(VL_PRECOCUSTO) FROM TB_PRODUTO


SELECT 
	ID_CATEGORIA,
	AVG(VL_PRECOCUSTO)
FROM TB_PRODUTO
GROUP BY ID_CATEGORIA
ORDER BY 1

SELECT 
	NM_PRODUTO,
	ID_CATEGORIA,
	VL_PRECOCUSTO,
	AVG(VL_PRECOCUSTO) OVER() VL_PRECOCUSTO_MEDIO_GERAL,
	AVG(VL_PRECOCUSTO) OVER( PARTITION BY ID_CATEGORIA) VL_PRECOCUSTO_MEDIO_CATEGORIA
FROM TB_PRODUTO

-- FUNÇÕES DE CLASSIFICAÇAO

-- ROW_NUMBER: numera sem repetir (toda a tabela ou a "janela")
SELECT 
	NM_PRODUTO,
	ID_CATEGORIA,
	VL_PRECOVENDA,
	ROW_NUMBER() OVER (ORDER BY VL_PRECOVENDA) POSICAO_NA_TABELA,
	ROW_NUMBER() OVER (PARTITION BY ID_CATEGORIA ORDER BY VL_PRECOVENDA) POSICAO_DENTRO_CATEGORIA
INTO #TB_PRODUTO_CLASSIFICADO
FROM TB_PRODUTO
ORDER BY POSICAO_DENTRO_CATEGORIA

SELECT * FROM #TB_PRODUTO_CLASSIFICADO
WHERE POSICAO_DENTRO_CATEGORIA = 1

-- RANK E DENSE_RANK
SELECT 
	NM_PRODUTO,
	ID_CATEGORIA,
	VL_PRECOVENDA,
	ROW_NUMBER() OVER (ORDER BY VL_PRECOVENDA) POSICAO_NA_TABELA,
	RANK() OVER (ORDER BY VL_PRECOVENDA) POSICAO_NA_TABELA_COM_EMPATE_E_PULO,
	DENSE_RANK() OVER (ORDER BY VL_PRECOVENDA) POSICAO_NA_TABELA_COM_EMPATE_SEM_PULO
FROM TB_PRODUTO
ORDER BY VL_PRECOVENDA

-- NTILE
SELECT
	NM_PRODUTO,
	ID_CATEGORIA,
	VL_PRECOVENDA,
	NTILE(4) OVER (ORDER BY VL_PRECOVENDA) AS GRUPOS
FROM TB_PRODUTO
ORDER BY VL_PRECOVENDA


-- FUNÇÕES ANALÍTICAS DE JANELA

-- PRIMEIRO E ULTIMO
SELECT 
 	NM_PRODUTO,
	ID_CATEGORIA,
	VL_PRECOVENDA,
	FIRST_VALUE (VL_PRECOVENDA) OVER (ORDER BY NM_PRODUTO) AS VALOR_PRIMEIRO_PRODUTO,
	FIRST_VALUE (VL_PRECOVENDA) OVER (PARTITION BY ID_CATEGORIA ORDER BY NM_PRODUTO) AS VALOR_PRIMEIRO_PRODUTO_CATEGORIA,
	FIRST_VALUE (VL_PRECOVENDA) OVER (ORDER BY NM_PRODUTO DESC) AS VALOR_ULTIMO_PRODUTO,
	FIRST_VALUE (VL_PRECOVENDA) OVER (PARTITION BY ID_CATEGORIA ORDER BY NM_PRODUTO DESC) AS VALOR_ULTIMO_PRODUTO_CATEGORIA,
	LAST_VALUE (VL_PRECOVENDA)  OVER (ORDER BY ID_CATEGORIA) AS VALOR_ULTIMO_PRODUTO_CATEGORIA
FROM TB_PRODUTO
ORDER BY ID_CATEGORIA, NM_PRODUTO

-- ANTERIOR E SEGUINTE
SELECT 
 	ID_VENDA,
	DT_VENDA,
	LEAD(DT_VENDA) OVER (ORDER BY DT_VENDA) DT_PROXIMA_VENDA,
	LAG(DT_VENDA) OVER (ORDER BY DT_VENDA) DT_VENDA_ANTERIOR,
	DATEDIFF(MINUTE,DT_VENDA,LEAD(DT_VENDA) OVER (ORDER BY DT_VENDA)) AS TEMPO_PROXIMA_VENDA
INTO #TEMPO_VENDA
FROM TB_VENDA
ORDER BY DT_VENDA



SELECT 
	AVG(TEMPO_PROXIMA_VENDA) AS MEDIA_TEMPO_VENDA
FROM #TEMPO_VENDA

SELECT 
	TB_ENDERECO.NM_ESTADO,
	AVG(TEMPO_PROXIMA_VENDA) AS TEMPO_MEDIO_VENDA
FROM #TEMPO_VENDA
	INNER JOIN TB_VENDA		ON #TEMPO_VENDA.ID_VENDA = TB_VENDA.ID_VENDA
	INNER JOIN TB_ENDERECO	ON TB_VENDA.ID_ENDERECOCOBRANCA = TB_ENDERECO.ID_ENDERECO
GROUP BY TB_ENDERECO.NM_ESTADO
ORDER BY TEMPO_MEDIO_VENDA

-- VALORES ACUMULADOS POR LINHA
SELECT 
	ID_VENDA,
	DT_VENDA,
	VL_SUBTOTAL,
	SUM(VL_SUBTOTAL) OVER (ORDER BY DT_VENDA) SUBTOTAL_VENDAS,
	SUM(VL_SUBTOTAL) OVER () TOTAL_VENDAS
FROM TB_VENDA
WHERE DT_VENDA BETWEEN '20210101' AND '20210131 23:59:59'
ORDER BY DT_VENDA

SELECT * FROM TB_VENDA