-- EXCLUINDO UMA TABELA
 DROP TABLE IF EXISTS TB_CURSO

-- CRIANDO A TB_CURSO
 CREATE TABLE TB_CURSO
(
	ID_CURSO				SMALLINT		IDENTITY,
	NM_TITULO				VARCHAR(30)		NOT NULL,
	DS_CURSO				VARCHAR(8000),
	VL_CARGA_HORARIA		TINYINT			NOT NULL CONSTRAINT DF_TB_CURSO_VL_CARGA_HORARI DEFAULT 40, 

	CONSTRAINT PK_TB_CURSO_ID_CURSO			PRIMARY KEY (ID_CURSO),
	CONSTRAINT UQ_TB_CURSO_NM_TITULO		UNIQUE		(NM_TITULO),
	CONSTRAINT CK_TB_CURSO_VL_CARGA_HORARIA CHECK	(VL_CARGA_HORARIA = 20 OR VL_CARGA_HORARIA = 40
													OR VL_CARGA_HORARIA = 80 OR VL_CARGA_HORARIA = 120)
)

-- SELECIONAR DADOS
SELECT * FROM TB_CURSO

INSERT INTO TB_CURSO VALUES ('EXCEL','MUITO BACANA',80)
INSERT INTO TB_CURSO (NM_TITULO) VALUES ('LÓGICA')

-- VIOLAÇÃO DA CHAVE ÚNICA ERRO PQ O VALOR LÓGICA JÁ EXISTE
INSERT INTO TB_CURSO VALUES ('LÓGICA','É SHOW',20)

-- FUNCIONA PQ 'LÓGICA' != ' LÓGICA'
INSERT INTO TB_CURSO VALUES (' LÓGICA','É SHOW',20)
INSERT INTO TB_CURSO VALUES ('LOGICA','É SHOW',20)

-- VIOLAÇÃO DA CHECK ERRO PQ NÃO PERMITE 50 HORAS COMO CARGA HORÁRIA
INSERT INTO TB_CURSO VALUES ('SQL','AMO MUITO', 50)

-- ALTERANDO A TABELA PARA INCLUSÃO DE CONSTRAINT
ALTER TABLE TB_PERIODO
	ADD
	CONSTRAINT PK_TB_PERIODO_ID_PERIODO PRIMARY KEY (ID_PERIODO),
	CONSTRAINT DF_TB_PERIODO_DS_PERIODO DEFAULT 'Matutino' FOR DS_PERIODO

-- INSERINDO VALORES
INSERT INTO TB_PERIODO VALUES ('Matutino')
INSERT INTO TB_PERIODO VALUES ('Vespertino')
INSERT INTO TB_PERIODO VALUES ('Noturno')
INSERT INTO TB_PERIODO VALUES ('Integral')

SELECT * FROM TB_PERIODO

-- ALTERANDO A TB_TURMA
ALTER TABLE TB_TURMA
	ADD	
	CONSTRAINT FK_TB_TURMA_TB_PERIODO FOREIGN KEY (ID_PERIODO) 
											REFERENCES TB_PERIODO (ID_PERIODO)

-- INSERINDO DADOS TB_TURMA
INSERT INTO TB_TURMA VALUES (25124,'2021/06/01',NULL,102,1)

SELECT * FROM TB_TURMA

-- VIOLAÇÃO DA CHAVE ESTRANGEIRA PQ NÃO EXISTE ID_PERIODO 1
INSERT INTO TB_TURMA VALUES (25125,'2021/08/01','2021/09/30',1,NULL)

