-- CRIANDO A PRIMEIRA TABELA
/* CRIANDO A 
PRIMEIRA TABELA*/
CREATE TABLE TB_CURSO -- NOME OBJETO COMEÇA COM LETRA, DEPOIS PODE TER LETRA, NUMERO E _
(
	ID_CURSO				INT, 
	NM_TITULO				VARCHAR(20),
	DS_CURSO				VARCHAR(8000),
	VL_CARGA_HORARIA		INT
)

CREATE TABLE TESTE 
(
	COLUNA1 INT
)

--ALTERANDO UMA TABELA ALTERANDO COLUNA
ALTER TABLE TB_CURSO
	ALTER COLUMN NM_TITULO VARCHAR(40)

--ALTERANDO UMA TABELA INCLUINDO COLUNA
ALTER TABLE TB_CURSO
	ADD VL_CURSO DECIMAL(6,2)  

-- RENOMEAR TABELA
SP_RENAME 'TB_CURSO', 'TB_CURSO2'

-- RENOMEAR COLUNA
SP_RENAME 'TB_CURSO.VL_CURSO', 'VL_CURSO2', 'COLUMN'

-- ALTERANDO UMA TABELA EXCLUINDO COLUNA
ALTER TABLE TB_CURSO
	DROP COLUMN VL_CURSO2

-- EXCLUINDO UMA TABELA
DROP TABLE TB_CURSO



