-- ALTERANDO O DATATYPE DAS COLUNAS ID_CURSO E VL_CARGA_HORARIA
CREATE TABLE TB_CURSO
(
	ID_CURSO				SMALLINT, -- -32MIL ATÉ +32 MIL
	NM_TITULO				VARCHAR(30),
	DS_CURSO				VARCHAR(8000),
	VL_CARGA_HORARIA		TINYINT, -- 0 ATÉ 255
)

--INCLUINDO VALOR DO CURSO
ALTER TABLE TB_CURSO
	ADD VL_PRECO	DECIMAL (7,2) -- -99 999.99 ATÉ +99 999.99
	
--INCLUINDO COLUNA CURSO ATIVO
ALTER TABLE TB_CURSO
	ADD FL_ATIVO BIT  -- 0 INATIVO E 1 ATIVO

--ALTERANDO VALOR DO CURSO PARA FLOAT DE 9 DIGITOS
ALTER TABLE TB_CURSO
	ALTER COLUMN VL_PRECO FLOAT(9)

--CRIANDO A TABELA TB_TURMA
CREATE TABLE TB_TURMA
(
	ID_TURMA	INT,
	DT_INICIO	DATE,
	DT_TERMINO	DATE,
	ID_PERIODO	TINYINT,
	ID_STATUS	TINYINT
)
	

-- CRIANDO A TABELA TB_STATUS
CREATE TABLE TB_STATUS
(	
	ID_STATUS	TINYINT,
	DS_STATUS	VARCHAR(20),	-- EM ANDAMENTO, ABERTA, FECHADA, CANCELADA
)
	

-- CRIANDO A TABELA TB_PERIODO
CREATE TABLE TB_PERIODO
(
	ID_PERIODO	TINYINT		IDENTITY,	-- AUTONUMERAVEL POR PADRAO DE 1 EM 1, PARA PERSONALIZAR IDENTITY( VALOR_INICIO, INCREMENTO) IDENTITY(100,2)
	DS_PERIODO	VARCHAR(20) NOT NULL	-- MATUTINO, VESPERTINO, NOTURO, INTEGRAL
)

-- ALTERANDO O DATA TYPE
ALTER TABLE TB_PERIODO
	ALTER COLUMN ID_PERIODO TINYINT

