-- TABELA CATEGORIA
CREATE TABLE TB_CATEGORIA
(
	ID_CATEGORIA			SMALLINT	IDENTITY,
	ID_CATEGORIA_SUPERIOR	SMALLINT	,
	NM_CATEGORIA			VARCHAR(30)	NOT NULL,

	CONSTRAINT PK_TB_CATEGORIA	PRIMARY KEY (ID_CATEGORIA),
	CONSTRAINT UQ_TB_CATEGORIA_NM_CATEGORIA UNIQUE (NM_CATEGORIA)
)

-- TABELA CLIENTE
CREATE TABLE TB_CLIENTE 
(
	ID_CLIENTE	INT				IDENTITY,
	NM_CLIENTE	VARCHAR(200)	NOT NULL,
	DS_EMAIL	VARCHAR(200)	NOT NULL, 
	NR_TELEFONE	VARCHAR(15)		NOT NULL,

	CONSTRAINT PK_TB_CLIENTE			 PRIMARY KEY (ID_CLIENTE),
	CONSTRAINT UQ_TB_CLIENTE_DS_EMAIL	 UNIQUE (DS_EMAIL),
	--CONSTRAINT CK_TB_CLIENTE_NR_TELEFONE CHECK (NR_TELEFONE BETWEEN '111111111111111' AND '999999999999999') 
	CONSTRAINT CK_TB_CLIENTE_NR_TELEFONE CHECK (NR_TELEFONE NOT LIKE '%[^0-9]%') 
)

--TESTANDO 
INSERT INTO TB_CLIENTE VALUES ('GUSTAVO','GFERREIRA@.COM','11999999999')
INSERT INTO TB_CLIENTE VALUES ('GUSTAVO','GFERR0@.COM','11111SSASA1')

SELECT * FROM TB_CLIENTE

-- TABELA ENDERECO
CREATE TABLE TB_ENDERECO
(
	ID_ENDERECO		INT				IDENTITY,
	DS_ENDERECO		VARCHAR(100)	NOT NULL,
	DS_COMPLEMENTO	VARCHAR(50),
	NM_CIDADE		VARCHAR(100)	NOT NULL,
	NM_ESTADO		VARCHAR(50)		NOT NULL,
	NM_PAIS			VARCHAR(50)		NOT NULL,
	CD_CODIGOPOSTAL	VARCHAR(20)		NOT NULL,

	CONSTRAINT PK_TB_ENDERECO		PRIMARY KEY (ID_ENDERECO),
	CONSTRAINT UQ_TB_ENDERECO		UNIQUE (DS_ENDERECO, DS_COMPLEMENTO, CD_CODIGOPOSTAL)
)

--TABELA ENDEREÇO CLIENTE
CREATE TABLE TB_ENDERECOCLIENTE
(	
	ID_CLIENTE		INT,
	ID_ENDERECO		INT,
	DS_TIPOENDERECO	VARCHAR(15),

	CONSTRAINT PK_ENDERECOCLIENTE				PRIMARY KEY (ID_CLIENTE,ID_ENDERECO),
	CONSTRAINT CK_ENDERECOCLIENTE_TIPOENDERECO	CHECK ( DS_TIPOENDERECO = 'RESIDENCIAL' OR DS_TIPOENDERECO = 'COMERCIAL')
)

-- TABELA PRODUTO
CREATE TABLE TB_PRODUTO
(
	ID_PRODUTO		INT				IDENTITY,
	NM_PRODUTO		VARCHAR(150)	NOT NULL,
	CD_PRODUTO		CHAR(13)		NOT NULL,
	DS_COR			VARCHAR(30)		NOT NULL,
	VL_PRECOCUSTO	DECIMAL(9,2)	NOT NULL,
	VL_PRECOVENDA	DECIMAL(9,2)	NOT NULL,
	VL_PESO			DECIMAL(9,3)	NOT NULL,
	ID_CATEGORIA	SMALLINT		NOT NULL,
	DT_INICIOVENDA	DATE			NOT NULL,
	DT_FIMVENDA		DATE,
	DS_ARQUIVOFOTO	VARCHAR(100),

	CONSTRAINT PK_TB_PRODUTO			   PRIMARY KEY (ID_PRODUTO),
	CONSTRAINT UQ_TB_PRODUTO_NM_PRODUTO	   UNIQUE (NM_PRODUTO),
	CONSTRAINT UQ_TB_PRODUTO_CD_PRODUTO	   UNIQUE (CD_PRODUTO),
	CONSTRAINT CK_TB_PRODUTO_VL_PRECOCUSTO CHECK (VL_PRECOCUSTO >= 0),
	CONSTRAINT CK_TB_PRODUTO_VL_PRECOVENDA CHECK (VL_PRECOVENDA >= 0),
	CONSTRAINT CK_TB_PRODUTO_VL_PESO	   CHECK (VL_PESO >= 0),
	CONSTRAINT CK_TB_PRODUTO_DT_FIMVENDA   CHECK (DT_FIMVENDA >= DT_INICIOVENDA)
)

-- TABELA VENDA
CREATE TABLE TB_VENDA
(
	ID_VENDA				BIGINT			IDENTITY,
	DT_VENDA				DATETIME2		NOT NULL CONSTRAINT DF_TB_VENDA DEFAULT GETDATE(),
	DT_ENVIO				DATETIME2,
	DT_ENTREGA				DATETIME2,
	DS_STATUS				VARCHAR(30)		NOT NULL,
	ID_CLIENTE				INT				NOT NULL,
	ID_ENDERECOENTREGA		INT				NOT NULL,
	ID_ENDERECOCOBRANCA		INT				NOT NULL,
	VL_SUBTOTAL				DECIMAL(9,2)	NOT NULL,
	VL_FRETE				DECIMAL(9,2)	NOT NULL,

	CONSTRAINT PK_TB_VENDA			 PRIMARY KEY (ID_VENDA),
	CONSTRAINT CK_TB_VENDA_DATAS	 CHECK (DT_ENVIO >= DT_VENDA 
										AND DT_ENTREGA >= DT_ENVIO) ,
	CONSTRAINT CK_TB_VENDA_DS_STATUS CHECK 
			(DS_STATUS = 'AGUARDANDO PAGAMENTO' OR 
			 DS_STATUS = 'EM TRANSPORTE' OR
			 DS_STATUS = 'ENTREGUE' OR
			 DS_STATUS = 'CANCELADO'),
/*
	DS_STATUS IN ( 'AGUARDANDO PAGAMENTO'
					,'EM TRANSPORTE' 
					,'ENTREGUE' 
					,'CANCELADO')
*/

	CONSTRAINT CK_TB_VENDA_VALORES	CHECK (VL_SUBTOTAL >= 0 AND
										  VL_FRETE >= 0)
)

-- TABELA VENDA ITEM
CREATE TABLE TB_VENDAITEM
(
	ID_VENDA			BIGINT,
	ID_VENDAITEM		SMALLINT,
	ID_PRODUTO			INT				NOT NULL,
	QT_ITEM				SMALLINT		NOT NULL,
	VL_PRECOUNITARIO	DECIMAL(9,2)	NOT NULL,
	VL_DESCONTOUNITARIO DECIMAL(9,2),

	CONSTRAINT PK_TB_ITEMVENDA			PRIMARY KEY (ID_VENDA, ID_VENDAITEM),
	CONSTRAINT CK_TB_ITEMVENDA_QT_ITEM  CHECK ( QT_ITEM > 0),
	CONSTRAINT CK_TB_ITEMVENDA_VALORES	CHECK (VL_PRECOUNITARIO > 0 AND
											VL_DESCONTOUNITARIO > 0)
)

-- CRIANDO AS FKs

ALTER TABLE TB_ENDERECOCLIENTE
  ADD
  CONSTRAINT FK_TB_ENDERECOCLIENTE_TB_CLIENTE 
	FOREIGN KEY (ID_CLIENTE)
		REFERENCES TB_CLIENTE (ID_CLIENTE),
 CONSTRAINT FK_TB_ENDERECOCLIENTE_TB_ENDERECO 
	FOREIGN KEY (ID_ENDERECO)
		REFERENCES TB_ENDERECO (ID_ENDERECO)

ALTER TABLE TB_PRODUTO
	ADD
	CONSTRAINT FK_TB_PRODUTO_TB_CATEGORIA
		FOREIGN KEY (ID_CATEGORIA)
			REFERENCES TB_CATEGORIA (ID_CATEGORIA)

ALTER TABLE TB_VENDA
	ADD
	CONSTRAINT FK_TB_VENDA_TB_CLIENTE
		FOREIGN KEY (ID_CLIENTE)
			REFERENCES TB_CLIENTE (ID_CLIENTE),
	CONSTRAINT FK_TB_VENDA_TB_ENDERECO_ENTREGA
		FOREIGN KEY (ID_ENDERECOENTREGA)
			REFERENCES TB_ENDERECO (ID_ENDERECO),
	CONSTRAINT FK_TB_VENDA_TB_ENDERECO_COBRANCA
		FOREIGN KEY (ID_ENDERECOCOBRANCA)
			REFERENCES TB_ENDERECO (ID_ENDERECO)

ALTER TABLE TB_VENDAITEM
	ADD
	CONSTRAINT FK_TB_VENDAITEM_TB_VENDA
		FOREIGN KEY (ID_VENDA)
			REFERENCES TB_VENDA (ID_VENDA),
	CONSTRAINT FK_TB_VENDAITEM_TB_PRODUTO
		FOREIGN KEY (ID_PRODUTO)
			REFERENCES TB_PRODUTO (ID_PRODUTO)

ALTER TABLE	TB_CATEGORIA
	ADD
	CONSTRAINT FK_TB_CATEGORIA
		FOREIGN KEY (ID_CATEGORIA_SUPERIOR)
			REFERENCES TB_CATEGORIA (ID_CATEGORIA)