--23/06/2021

-- IF EXISTS

--CRIANDO A TB_CURSO
CREATE TABLE TB_CURSO
(
	ID_CURSO SMALLINT IDENTITY, -- VAI DE -32MIL ATÉ +32MIL
	NM_TITULO VARCHAR(30) NOT NULL,
	DS_CURSO VARCHAR(8000),
	VL_CARGA_HORARIA TINYINT NOT NULL CONSTRAINT DF_TB_CURSO_VL_CARGA_HORARIA DEFAULT 40, --DE 0 A 255

	CONSTRAINT PK_TB_CURSO_ID_CURSO PRIMARY KEY(ID_CURSO),
	CONSTRAINT UQ_TB_CURSO_NM_TITULO UNIQUE(NM_TITULO),
	CONSTRAINT CK_TB_CURSO_VL_CARGA_HORARIA CHECK (VL_CARGA_HORARIA = 20 OR VL_CARGA_HORARIA = 40 
													OR VL_CARGA_HORARIA = 80 OR VL_CARGA_HORARIA = 120 )
);

--SELECIONAR DADOS
SELECT * FROM TB_CURSO;

INSERT INTO TB_CURSO VALUES ('EXEL', 'MUITO BACANA!', 80);
INSERT INTO TB_CURSO (NM_TITULO) VALUES('LÓGICA');

drop table TB_CURSO;
