/*CREATE TABLE TB_CURSO --NOME DE OBJETO COMEÇA COM LETRA, DEPOIS PODE TER LETRA, NÚMERO E ANDERLINE(_)
(
	ID_CURSO          INT, 
	NM_TITULO         VARCHAR(20),
	DS_CURSO          VARCHAR(8000),
	VL_CARGA_HORARIA  INT
);*/

--ALTERANDO DATATYPE DAS COLUNAS ID_CURSO E VL_CARGA_HORARIA
CREATE TABLE TB_CURSO
(
	ID_CURSO SMALLINT, -- VAI DE -32MIL ATÉ +32MIL
	NM_TITULO VARCHAR(20),
	DS_CURSO VARCHAR(8000),
	VL_CARGA_HORARIA SMALLINT --DE 0 A 255
);

--INCLUINDO VALOR DO CURSO
ALTER TABLE TB_CURSO
   ADD VL_PRECO DECIMAL(9,2) -- -9 999 999.99 ATÉ +9 999 999.99

   --INCLUINDO COLUNA CORSO_ATIVO
   ALTER TABLE TB_CURSO
      ADD FL_ATIVO BIT -- 0 INATIVO E 1 ATIVO

--CRIANDO A TABELA TB_TURMA
CREATE TABLE TB_TURMA
(
	ID_TURMA INT,
	DT_INICIO DATE,
	DT_TERMINO DATE,
	ID_PERIODO TINYINT,
	ID_STATUS TINYINT
);


/*
DIFERENCA ENTRE CHAR E VARCHAR
CHAR(10)   'EXEL     '
VARCHAR(10) 'EXEL' 
*/

--CRIANDO TABELA TB_STATUS
CREATE TABLE TB_STATUS
(
	ID_STATUS TINYINT,
	DS_STATUS VARCHAR(20), --ANDAMENTO ABERTA FECHADA CANCELADA
);
--CRIANDO A TABELA TB_PERIODO
CREATE TABLE TB_PERIODO
(
	ID_PERIODO TINYINT  IDENTITY(100,2), --AUTONUMERÁVEL(COMECA, INCREMENTO)
	DS_PERIODO VARCHAR(20) NOT NULL,
);







