--Coloque o banco DB_MADA_VAREJO em uso
USE DB_MADA_VAREJO

--Quantas compras foram entregues na cidade de Osasco?
SELECT 
	COUNT(*) AS QT_VENDAS
FROM TB_VENDA
	INNER JOIN TB_ENDERECO 
		ON TB_VENDA.ID_ENDERECOENTREGA = TB_ENDERECO.ID_ENDERECO
WHERE DS_STATUS = 'ENTREGUE' 
AND NM_CIDADE = 'OSASCO'

SELECT 
	TB_ENDERECO.NM_CIDADE,
	COUNT(*) AS QT_VENDAS
FROM TB_VENDA
	INNER JOIN TB_ENDERECO 
		ON TB_VENDA.ID_ENDERECOENTREGA = TB_ENDERECO.ID_ENDERECO
WHERE DS_STATUS = 'ENTREGUE' 
AND NM_CIDADE = 'OSASCO'
GROUP BY TB_ENDERECO.NM_CIDADE

-- Qual produto teve o maior valor vendido (quantidade multiplicada pelo valor unitário abatido do desconto) 
-- no segundo quadrimestre de 2020?
SELECT TOP 1
	TB_PRODUTO.ID_PRODUTO,
	TB_PRODUTO.NM_PRODUTO,
	SUM	( QT_ITEM * (VL_PRECOUNITARIO - ISNULL(VL_DESCONTOUNITARIO,0)) ) AS VL_VENDIDO,
	SUM (QT_ITEM) AS QT_VENDIDA
FROM TB_PRODUTO	
	JOIN TB_VENDAITEM 
		ON TB_PRODUTO.ID_PRODUTO = TB_VENDAITEM.ID_PRODUTO
	JOIN TB_VENDA
		ON TB_VENDA.ID_VENDA = TB_VENDAITEM.ID_VENDA
WHERE DT_VENDA BETWEEN '20200501' AND '20200831 23:59:59'
GROUP BY 
	TB_PRODUTO.ID_PRODUTO,
	TB_PRODUTO.NM_PRODUTO
ORDER BY VL_VENDIDO DESC

--Qual a categoria tem o maior volume (quantidade)  de vendas? E qual categoria tem o menor volume?

SELECT TOP 1
	TB_CATEGORIA.ID_CATEGORIA,
	TB_CATEGORIA.NM_CATEGORIA,
	SUM(QT_ITEM) QT_VENDAS
 FROM TB_CATEGORIA	
	INNER JOIN TB_PRODUTO
		ON TB_CATEGORIA.ID_CATEGORIA = TB_PRODUTO.ID_CATEGORIA
	INNER JOIN TB_VENDAITEM
		ON TB_VENDAITEM.ID_PRODUTO = TB_PRODUTO.ID_PRODUTO
GROUP BY 
	TB_CATEGORIA.ID_CATEGORIA,
	TB_CATEGORIA.NM_CATEGORIA
ORDER BY QT_VENDAS DESC -- ORDENAR DO MAIOR PARA O MENOR


SELECT TOP 1
	TB_CATEGORIA.ID_CATEGORIA,
	TB_CATEGORIA.NM_CATEGORIA,
	SUM(QT_ITEM) QT_VENDAS
 FROM TB_CATEGORIA	
	INNER JOIN TB_PRODUTO
		ON TB_CATEGORIA.ID_CATEGORIA = TB_PRODUTO.ID_CATEGORIA
	INNER JOIN TB_VENDAITEM
		ON TB_VENDAITEM.ID_PRODUTO = TB_PRODUTO.ID_PRODUTO
GROUP BY 
	TB_CATEGORIA.ID_CATEGORIA,
	TB_CATEGORIA.NM_CATEGORIA
ORDER BY QT_VENDAS -- ORDENAR DO MENOR PARA O MAIOR

--Quais clientes possuem mais de um endereço?
SELECT
 TB_CLIENTE.ID_CLIENTE,
 TB_CLIENTE.NM_CLIENTE,
 COUNT(*)			AS QTD_REGISTROS,
 COUNT(TB_ENDERECOCLIENTE.ID_ENDERECO) AS QTD_ENDERECO
FROM TB_CLIENTE
	LEFT JOIN TB_ENDERECOCLIENTE
		ON TB_CLIENTE.ID_CLIENTE = TB_ENDERECOCLIENTE.ID_CLIENTE
GROUP BY  
 TB_CLIENTE.ID_CLIENTE,
 TB_CLIENTE.NM_CLIENTE
HAVING COUNT(TB_ENDERECOCLIENTE.ID_ENDERECO) > 1
