--Crie um script SQL utilizando apenas SUBQUERY que retorne todos clientes que compraram 
-- o produto “Hd Seagate Externo Portatil Lacie 2tb Sthg2000400 –” e
-- “Mesa de Cabeceira com Casinha para Cachorro Gato Pet - Branco – Ofertamo”.

-- SÓ SUBQUERY
SELECT * FROM TB_CLIENTE
WHERE ID_CLIENTE IN -- CLIENTES QUE COMPRARAM O HD 
 (SELECT ID_CLIENTE FROM TB_VENDA
  WHERE ID_VENDA IN 
	(SELECT ID_VENDA FROM TB_VENDAITEM
	 WHERE ID_PRODUTO = 
		(SELECT ID_PRODUTO FROM TB_PRODUTO
		 WHERE NM_PRODUTO = 'Hd Seagate Externo Portatil Lacie 2tb Sthg2000400 -')
	)
  )
AND 
ID_CLIENTE IN -- CLIENTES QUE COMPRARAM MESA DE CABECEIRA PARA CACHORRO 
 (SELECT ID_CLIENTE FROM TB_VENDA
  WHERE ID_VENDA IN 
	(SELECT ID_VENDA FROM TB_VENDAITEM
	 WHERE ID_PRODUTO = 
		(SELECT ID_PRODUTO FROM TB_PRODUTO
		 WHERE NM_PRODUTO = 'Mesa de Cabeceira com Casinha para Cachorro Gato Pet - Branco - Ofertamo')
	)
  )


-- SUBQUERY + JOIN
SELECT * FROM TB_CLIENTE
WHERE 
ID_CLIENTE IN 
-- CLIENTES QUE COMPRARAM O HD 
	 (SELECT ID_CLIENTE FROM TB_VENDA
	  INNER JOIN TB_VENDAITEM
		 ON TB_VENDA.ID_VENDA = TB_VENDAITEM.ID_VENDA
	  INNER JOIN TB_PRODUTO
		ON TB_PRODUTO.ID_PRODUTO = TB_VENDAITEM.ID_PRODUTO	 
	   WHERE NM_PRODUTO = 'Hd Seagate Externo Portatil Lacie 2tb Sthg2000400 -')
AND 
ID_CLIENTE IN -- CLIENTES QUE COMPRARAM MESA CABECEIRA PARA CACHORRO
	 (SELECT ID_CLIENTE FROM TB_VENDA
	  INNER JOIN TB_VENDAITEM
		 ON TB_VENDA.ID_VENDA = TB_VENDAITEM.ID_VENDA
	  INNER JOIN TB_PRODUTO
		ON TB_PRODUTO.ID_PRODUTO = TB_VENDAITEM.ID_PRODUTO	 
	  WHERE NM_PRODUTO = 'Mesa de Cabeceira com Casinha para Cachorro Gato Pet - Branco - Ofertamo')


 -- SOMENTE JOIN 
 SELECT 
	TB_CLIENTE.ID_CLIENTE, 
	TB_CLIENTE.NM_CLIENTE, 
	COUNT(DISTINCT TB_PRODUTO.ID_PRODUTO) AS QTD_PRODUTOS_DIF
  FROM TB_VENDA
  INNER JOIN TB_VENDAITEM
	 ON TB_VENDA.ID_VENDA = TB_VENDAITEM.ID_VENDA
  INNER JOIN TB_PRODUTO
	ON TB_PRODUTO.ID_PRODUTO = TB_VENDAITEM.ID_PRODUTO	 
  INNER JOIN TB_CLIENTE
	ON TB_CLIENTE.ID_CLIENTE = TB_VENDA.ID_CLIENTE
WHERE  NM_PRODUTO = 'Mesa de Cabeceira com Casinha para Cachorro Gato Pet - Branco - Ofertamo'
OR NM_PRODUTO = 'Hd Seagate Externo Portatil Lacie 2tb Sthg2000400 -'
GROUP BY 	
	TB_CLIENTE.ID_CLIENTE, 
	TB_CLIENTE.NM_CLIENTE
HAVING COUNT(DISTINCT TB_PRODUTO.ID_PRODUTO) = 2

--Crie um script SQL utilizando apenas SUBQUERY que retorne todos clientes que compraram 
-- o produto “Hd Seagate Externo Portatil Lacie 2tb Sthg2000400 –” , MAS NÃO COMPRARAM
-- “Mesa de Cabeceira com Casinha para Cachorro Gato Pet - Branco – Ofertamo”.

-- SUBQUERY + JOIN
SELECT * FROM TB_CLIENTE
WHERE ID_CLIENTE IN -- CLIENTES QUE COMPRARAM O HD 
 (SELECT ID_CLIENTE FROM TB_VENDA
  INNER JOIN TB_VENDAITEM
	 ON TB_VENDA.ID_VENDA = TB_VENDAITEM.ID_VENDA
  INNER JOIN TB_PRODUTO
	ON TB_PRODUTO.ID_PRODUTO = TB_VENDAITEM.ID_PRODUTO	 
   WHERE NM_PRODUTO = 'Hd Seagate Externo Portatil Lacie 2tb Sthg2000400 -')
AND 
ID_CLIENTE NOT IN -- CLIENTES QUE COMPRARAM MESA CABECEIRA, SÓ QUE NÃO
 (SELECT ID_CLIENTE FROM TB_VENDA
  INNER JOIN TB_VENDAITEM
	 ON TB_VENDA.ID_VENDA = TB_VENDAITEM.ID_VENDA
  INNER JOIN TB_PRODUTO
	ON TB_PRODUTO.ID_PRODUTO = TB_VENDAITEM.ID_PRODUTO	 
  WHERE NM_PRODUTO = 'Mesa de Cabeceira com Casinha para Cachorro Gato Pet - Branco - Ofertamo')

SELECT * FROM TB_CLIENTE
WHERE ID_CLIENTE IN -- CLIENTES QUE COMPRARAM O HD 
 (SELECT ID_CLIENTE FROM TB_VENDA
  INNER JOIN TB_VENDAITEM
	 ON TB_VENDA.ID_VENDA = TB_VENDAITEM.ID_VENDA
  INNER JOIN TB_PRODUTO
	ON TB_PRODUTO.ID_PRODUTO = TB_VENDAITEM.ID_PRODUTO	 
   WHERE NM_PRODUTO = 'Hd Seagate Externo Portatil Lacie 2tb Sthg2000400 -'
	
	EXCEPT
	
 SELECT ID_CLIENTE FROM TB_VENDA -- CLIENTES QUE COMPRARAM MESA DE CABECEIRA 
  INNER JOIN TB_VENDAITEM
	 ON TB_VENDA.ID_VENDA = TB_VENDAITEM.ID_VENDA
  INNER JOIN TB_PRODUTO
	ON TB_PRODUTO.ID_PRODUTO = TB_VENDAITEM.ID_PRODUTO	 
  WHERE NM_PRODUTO = 'Mesa de Cabeceira com Casinha para Cachorro Gato Pet - Branco - Ofertamo')

