USE DB_MADA_VAREJO

-- SUBQUERY 

-- SELECT DENTRO DE SELECT

-- SELECT COMO "TABELA"
SELECT
 ANO_VENDA, MES_VENDA, ESTADO_ENTREGA, VL_VENDA
FROM 
	(
	SELECT 
	*,
	MAX(VL_VENDA) OVER (PARTITION BY ANO_VENDA, ESTADO_ENTREGA) AS MAX_VL_VENDA
	FROM 
		(SELECT 
			YEAR(DT_VENDA)  AS ANO_VENDA,
			MONTH(DT_VENDA) AS MES_VENDA,
			NM_ESTADO		AS ESTADO_ENTREGA,
			SUM(VL_SUBTOTAL + VL_FRETE) AS VL_VENDA
		FROM TB_VENDA
			INNER JOIN TB_ENDERECO 
				ON ID_ENDERECOENTREGA = ID_ENDERECO
		WHERE NM_ESTADO IN ('PR','SC','RS')
		GROUP BY 
			YEAR(DT_VENDA),	MONTH(DT_VENDA), NM_ESTADO ) AS TABELA
  ) AS TABELA_2
WHERE VL_VENDA = MAX_VL_VENDA

-- SELECT NO WHERE
-- CLIENTES QUE COMPRARAM EM JUNHO/21, MAS NÃO COMPRARAM EM JULHO/21
-- CLIENTES COM ID 1,2,3,4,5 MAS NÃO QUERO OS COM ID 4,5
SELECT * FROM TB_CLIENTE
WHERE ID_CLIENTE 
  IN (SELECT ID_CLIENTE FROM TB_VENDA WHERE DT_VENDA BETWEEN '20210601' AND '20210630 23:59:59') -- COMPROU EM JUNHO/21
AND ID_CLIENTE 
 NOT IN (SELECT ID_CLIENTE FROM TB_VENDA WHERE DT_VENDA BETWEEN '20210701' AND '20210731 23:59:59') -- COMPRARAM EM JULHO/21, SÓ QUE NÃO

SELECT * FROM TB_CLIENTE
WHERE ID_CLIENTE IN
 ( SELECT ID_CLIENTE FROM TB_VENDA WHERE DT_VENDA BETWEEN '20210601' AND '20210630 23:59:59'
	EXCEPT
   SELECT ID_CLIENTE FROM TB_VENDA WHERE DT_VENDA BETWEEN '20210701' AND '20210731 23:59:59')


 -- CLAUSULA EXISTS
SELECT * FROM TB_CLIENTE
WHERE  EXISTS
	(SELECT * FROM TB_VENDA 
	  WHERE DT_VENDA BETWEEN '20210601' AND '20210630 23:59:59'
	  AND TB_CLIENTE.ID_CLIENTE = TB_VENDA.ID_CLIENTE ) -- COMPROU EM JUNHO/21
AND NOT EXISTS
	(SELECT * FROM TB_VENDA 
	WHERE DT_VENDA BETWEEN '20210701' AND '20210731 23:59:59'
	AND 1 = TB_VENDA.ID_CLIENTE ) -- COMPRARAM EM JULHO/21, SÓ QUE NÃO

-- 

-- SELECT NA COLUNA
-- CLIENTE QUE MAIS GASTOU
SELECT *, 
	(SELECT SUM(VL_SUBTOTAL+VL_FRETE)  FROM TB_VENDA WHERE TB_VENDA.ID_CLIENTE = TB_CLIENTE.ID_CLIENTE) 
		AS tot_gasto
	FROM TB_CLIENTE
WHERE ID_CLIENTE = (SELECT TOP 1 ID_CLIENTE FROM TB_VENDA
					GROUP BY ID_CLIENTE
					ORDER BY SUM(VL_SUBTOTAL+VL_FRETE) DESC)

SELECT TOP 1 TB_CLIENTE.*, SUM(VL_SUBTOTAL+VL_FRETE) AS TOT_GASTO FROM TB_CLIENTE
	JOIN TB_VENDA ON TB_CLIENTE.ID_CLIENTE = TB_VENDA.ID_CLIENTE
GROUP BY TB_CLIENTE.ID_CLIENTE, TB_CLIENTE.NM_CLIENTE, TB_CLIENTE.DS_EMAIL, TB_CLIENTE.NR_TELEFONE
ORDER BY SUM(VL_SUBTOTAL+VL_FRETE) DESC


-- SELECT NO UPDATE
SELECT * FROM TB_VENDA
WHERE ID_VENDA = (SELECT MAX(ID_VENDA) FROM TB_VENDA)

SELECT * FROM TB_VENDAITEM
WHERE ID_VENDA = 39

UPDATE TB_VENDA
SET VL_SUBTOTAL = (SELECT SUM( QT_ITEM * (VL_PRECOUNITARIO - ISNULL(VL_DESCONTOUNITARIO,0) )) 
					FROM TB_VENDAITEM
					WHERE TB_VENDAITEM.ID_VENDA = TB_VENDA.ID_VENDA)
WHERE ID_VENDA = (SELECT MAX(ID_VENDA) FROM TB_VENDA)

-- SELECT NO DELETE
-- EXCLUIR OS ITENS DE VENDA DAS VENDAS DE JANEIRO/2019
DELETE FROM TB_VENDAITEM
WHERE ID_VENDA IN (SELECT ID_VENDA FROM TB_VENDA
					WHERE DT_VENDA BETWEEN '20190101' AND '20190131 23:59:59')

-- SELECT NO INSERT
INSERT INTO TB_PRODUTO_CLASSIFICADO
SELECT TOP 3 NM_PRODUTO, ID_CATEGORIA, VL_PRECOVENDA, NULL, NULL
FROM TB_PRODUTO
ORDER BY NEWID()