-- Coloque o banco DB_MADA_VAREJO em uso
USE DB_MADA_VAREJO

--Exibir quais os meses tiveram vendas em 2019 e que não tiveram vendas em 2020 na cidade de Blumenau. 
SELECT
	MONTH(TB_VENDA.DT_VENDA)
FROM TB_VENDA
	INNER JOIN TB_ENDERECO	
		ON TB_VENDA.ID_ENDERECOCOBRANCA = TB_ENDERECO.ID_ENDERECO
WHERE YEAR(TB_VENDA.DT_VENDA) = 2019
AND TB_ENDERECO.NM_CIDADE = 'BLUMENAU'
EXCEPT
SELECT 
	MONTH(TB_VENDA.DT_VENDA)
FROM TB_VENDA
	INNER JOIN TB_ENDERECO	
		ON TB_VENDA.ID_ENDERECOCOBRANCA = TB_ENDERECO.ID_ENDERECO
WHERE YEAR(TB_VENDA.DT_VENDA) = 2020
AND TB_ENDERECO.NM_CIDADE = 'BLUMENAU'

-- Exibir os produtos que estavam no TOP 10 dos mais vendidos em Maio de 2021 
-- e que também estavam nos TOP 10 dos mais vendidos em Junho de 2021. 
-- (dica utilize tabela temporária para  cada etapa)

-- RESOLUÇÃO PARA VALOR
SELECT TOP 10 
	TB_PRODUTO.ID_PRODUTO,
	TB_PRODUTO.NM_PRODUTO,
	SUM( (TB_VENDAITEM.VL_PRECOUNITARIO - ISNULL(TB_VENDAITEM.VL_DESCONTOUNITARIO,0)) * TB_VENDAITEM.QT_ITEM)
	 AS VALOR_VENDIDO
INTO #TOP10_MAIO21 -- DROP TABLE #TOP10_MAIO21 
FROM TB_PRODUTO
	INNER JOIN TB_VENDAITEM 
		ON TB_PRODUTO.ID_PRODUTO = TB_VENDAITEM.ID_PRODUTO
	INNER JOIN TB_VENDA
		ON TB_VENDA.ID_VENDA = TB_VENDAITEM.ID_VENDA
WHERE DT_VENDA BETWEEN '20210501' AND '20210531 23:59:59'
GROUP BY TB_PRODUTO.ID_PRODUTO,TB_PRODUTO.NM_PRODUTO
ORDER BY 
SUM( (TB_VENDAITEM.VL_PRECOUNITARIO - ISNULL(TB_VENDAITEM.VL_DESCONTOUNITARIO,0)) * TB_VENDAITEM.QT_ITEM) DESC

SELECT TOP 10 
	TB_PRODUTO.ID_PRODUTO,
	TB_PRODUTO.NM_PRODUTO,
	SUM( (TB_VENDAITEM.VL_PRECOUNITARIO - ISNULL(TB_VENDAITEM.VL_DESCONTOUNITARIO,0)) * TB_VENDAITEM.QT_ITEM)
	 AS VALOR_VENDIDO
INTO #TOP10_JUNHO21 -- DROP TABLE #TOP10_JUNHO21 
FROM TB_PRODUTO
	INNER JOIN TB_VENDAITEM 
		ON TB_PRODUTO.ID_PRODUTO = TB_VENDAITEM.ID_PRODUTO
	INNER JOIN TB_VENDA
		ON TB_VENDA.ID_VENDA = TB_VENDAITEM.ID_VENDA
WHERE DT_VENDA BETWEEN '20210601' AND '20210630 23:59:59'
GROUP BY TB_PRODUTO.ID_PRODUTO,TB_PRODUTO.NM_PRODUTO
ORDER BY 
SUM( (TB_VENDAITEM.VL_PRECOUNITARIO - ISNULL(TB_VENDAITEM.VL_DESCONTOUNITARIO,0)) * TB_VENDAITEM.QT_ITEM) DESC

SELECT NM_PRODUTO FROM #TOP10_MAIO21
INTERSECT
SELECT NM_PRODUTO FROM #TOP10_JUNHO21 	 

-- RESOLUÇÃO PARA VALOR
SELECT TOP 10 
	TB_PRODUTO.ID_PRODUTO,
	TB_PRODUTO.NM_PRODUTO,
	SUM(TB_VENDAITEM.QT_ITEM) AS QTD_VENDIDO
INTO #TOP10_MAIO21_QTD -- DROP TABLE #TOP10_MAIO21_QTD
FROM TB_PRODUTO
	INNER JOIN TB_VENDAITEM 
		ON TB_PRODUTO.ID_PRODUTO = TB_VENDAITEM.ID_PRODUTO
	INNER JOIN TB_VENDA
		ON TB_VENDA.ID_VENDA = TB_VENDAITEM.ID_VENDA
WHERE DT_VENDA BETWEEN '20210501' AND '20210531 23:59:59'
GROUP BY TB_PRODUTO.ID_PRODUTO,TB_PRODUTO.NM_PRODUTO
ORDER BY SUM( TB_VENDAITEM.QT_ITEM) DESC

SELECT TOP 10 
	TB_PRODUTO.ID_PRODUTO,
	TB_PRODUTO.NM_PRODUTO,
	SUM(TB_VENDAITEM.QT_ITEM) AS QTD_VENDIDO
INTO #TOP10_JUNHO21_QTD -- DROP TABLE #TOP10_JUNHO21_QTD 
FROM TB_PRODUTO
	INNER JOIN TB_VENDAITEM 
		ON TB_PRODUTO.ID_PRODUTO = TB_VENDAITEM.ID_PRODUTO
	INNER JOIN TB_VENDA
		ON TB_VENDA.ID_VENDA = TB_VENDAITEM.ID_VENDA
WHERE DT_VENDA BETWEEN '20210601' AND '20210630 23:59:59'
GROUP BY TB_PRODUTO.ID_PRODUTO,TB_PRODUTO.NM_PRODUTO
ORDER BY SUM(TB_VENDAITEM.QT_ITEM) DESC

SELECT NM_PRODUTO FROM #TOP10_MAIO21_QTD
INTERSECT
SELECT NM_PRODUTO FROM #TOP10_JUNHO21_QTD 	 


-- Dos clientes que compraram, qual foi o que mais gastou e o que menos gastou em 2020?
SELECT TOP 1
	TB_CLIENTE.NM_CLIENTE,
	SUM(VL_SUBTOTAL + VL_FRETE) AS TOTAL_COMPRADO
INTO #CLI_MAIS_COMPROU
FROM TB_CLIENTE
	INNER JOIN TB_VENDA ON TB_CLIENTE.ID_CLIENTE = TB_VENDA.ID_CLIENTE
WHERE TB_VENDA.DT_VENDA BETWEEN '20200101' AND '20201231 23:59:59'
GROUP BY TB_CLIENTE.NM_CLIENTE
ORDER BY TOTAL_COMPRADO DESC -- MAIS COMPROU


SELECT TOP 1
	TB_CLIENTE.NM_CLIENTE,
	SUM(VL_SUBTOTAL + VL_FRETE) AS TOTAL_COMPRADO
INTO #CLI_MENOS_COMPROU
FROM TB_CLIENTE
	INNER JOIN TB_VENDA ON TB_CLIENTE.ID_CLIENTE = TB_VENDA.ID_CLIENTE
WHERE TB_VENDA.DT_VENDA BETWEEN '20200101' AND '20201231 23:59:59'
GROUP BY TB_CLIENTE.NM_CLIENTE
ORDER BY TOTAL_COMPRADO -- MENOS COMPROU


SELECT * FROM #CLI_MAIS_COMPROU
UNION
SELECT * FROM #CLI_MENOS_COMPROU