--Mão na massa – Individual

--Coloque o banco DB_MADA_VAREJO em uso
USE DB_MADA_VAREJO


/*1. Exibir quais os meses tiveram vendas em 2019 e que
não tiveram vendas em 2020 na cidade de Blumenau.*/
SELECT 
	MONTH(TB_VENDA.DT_VENDA) MES_VENDA,
	YEAR(TB_VENDA.DT_VENDA) ANO_VENDA,
	TB_ENDERECO.NM_CIDADE
FROM TB_VENDA
INNER JOIN TB_ENDERECO
	ON  TB_VENDA.ID_ENDERECOENTREGA = TB_ENDERECO.ID_ENDERECO
WHERE TB_VENDA.DT_VENDA BETWEEN '20190101' AND '20190131 23:59:59' AND TB_ENDERECO.NM_CIDADE = 'Blumenau'
EXCEPT
SELECT 
	MONTH(TB_VENDA.DT_VENDA) MES_VENDA,
	YEAR(TB_VENDA.DT_VENDA) ANO_VENDA,
	TB_ENDERECO.NM_CIDADE
FROM TB_VENDA
INNER JOIN TB_ENDERECO
	ON  TB_VENDA.ID_ENDERECOENTREGA = TB_ENDERECO.ID_ENDERECO
WHERE TB_VENDA.DT_VENDA BETWEEN '20200101' AND '20200131 23:59:59' AND TB_ENDERECO.NM_CIDADE = 'Blumenau'


--correção
SELECT 
	MONTH(TB_VENDA.DT_VENDA) MES_VENDA
FROM TB_VENDA
INNER JOIN TB_ENDERECO
	ON  TB_VENDA.ID_ENDERECOENTREGA = TB_ENDERECO.ID_ENDERECO
WHERE YEAR(TB_VENDA.DT_VENDA) = '2019' AND TB_ENDERECO.NM_CIDADE = 'Blumenau'
EXCEPT
SELECT 
	MONTH(TB_VENDA.DT_VENDA) MES_VENDA
FROM TB_VENDA
INNER JOIN TB_ENDERECO
	ON  TB_VENDA.ID_ENDERECOENTREGA = TB_ENDERECO.ID_ENDERECO
WHERE YEAR(TB_VENDA.DT_VENDA) = '2020' AND TB_ENDERECO.NM_CIDADE = 'Blumenau'


/*2. Exibir os produtos que estavam no TOP 10 dos mais
vendidos em Maio de 2021 e que também estavam nos
TOP 10 dos mais vendidos em Junho de 2021. (dica
utilize tabela temporária para cada etapa)*/

SELECT TOP 10 
	*
FROM TB_PRODUTO
INNER JOIN TB_VENDAITEM
	ON TB_PRODUTO.ID_PRODUTO = TB_VENDAITEM.ID_PRODUTO



/*3. Dos clientes que compraram, qual foi o que mais gastou
e o que menos gastou em 2020?*/
SELECT 
	TB_CLIENTE.ID_CLIENTE,
	TB_CLIENTE.NM_CLIENTE,
	TB_VENDA.DT_VENDA,
	TB_VENDA.VL_SUBTOTAL
FROM TB_CLIENTE
	INNER JOIN TB_VENDA 
		ON TB_CLIENTE.ID_CLIENTE = TB_VENDA.ID_CLIENTE
WHERE YEAR(TB_VENDA.DT_VENDA) = '2020' 
