-- VERIFICA METADADOS DO OBJETO
SP_HELP TB_TURMA

-- INSERINDO UM UNICO REGISTRO NA TABELA CURSO (POSICIONAL)
INSERT INTO TB_CURSO VALUES ('ACADEMIA MARKETDATA','FORMAÇÃO PROFISSIONAL', 120) -- INTO É OPCIONAL

-- VISUALIZAR / SELECIONAR DADOS
SELECT * FROM TB_CURSO


-- INSERINDO VÁRIOS REGISTROS (POSICIONAL)
INSERT INTO TB_TURMA VALUES 
	(157,'2021/06/01','2021/07/16',102,1),
	(158,'2021/08/01','2021/09/15',102,2),
	(159,'2021/10/01','2021/11/14',100,2)

-- INSERT DECLARATIVO (INFORMO NO COMANDO AS COLUNAS)
INSERT TB_CURSO (NM_TITULO) VALUES ('ANALYTICS BÁSICO')

INSERT TB_CURSO (NM_TITULO) VALUES ('PLANEJAMENTO'), ('CRM'), ('LGPD')

--INSERINDO COM SELECT
INSERT INTO TB_TURMA -- INTO É OPCIONAL
SELECT * FROM TB_TURMA

CREATE TABLE [dbo].[TB_CURSO_NOVOS](
	[ID_CURSO] [smallint] ,
	[NM_TITULO] [varchar](30) ,
	[DS_CURSO] [varchar](8000) ,
	[VL_CARGA_HORARIA] [tinyint] ,
)

INSERT INTO TB_CURSO_NOVOS 
	SELECT * FROM TB_CURSO


CREATE TABLE [dbo].[TB_CURSOS_40](
	[ID_CURSO] [smallint] ,
	[NM_TITULO] [varchar](30) ,
	[DS_CURSO] [varchar](8000) ,
	[VL_CARGA_HORARIA] [tinyint] ,
)

INSERT INTO TB_CURSOS_40 
	SELECT * FROM TB_CURSO_NOVOS 
	WHERE VL_CARGA_HORARIA = 40


-- CRIANDO UMA TABELA COM SELECT 
SELECT * INTO TB_CURSO_AUX FROM TB_CURSO

SELECT * FROM TB_CURSO_AUX

SELECT * INTO TB_CURSOS_40 FROM TB_CURSO_NOVOS 
	WHERE VL_CARGA_HORARIA = 40


-- ATUALIZANDO DADOS DE UMA COLUNA
UPDATE TB_CURSO_AUX
SET VL_CARGA_HORARIA = VL_CARGA_HORARIA + 5
--OU
UPDATE TB_CURSO_AUX
SET VL_CARGA_HORARIA += 5

UPDATE TB_CURSO_AUX
SET VL_CARGA_HORARIA = VL_CARGA_HORARIA - 2
--OU
UPDATE TB_CURSO_AUX
SET VL_CARGA_HORARIA -= 2

UPDATE TB_CURSO_AUX 
SET VL_CARGA_HORARIA = 180
WHERE NM_TITULO = 'ACADEMIA MARKETDATA'

-- ATUALIZANDO DADOS DE + DE UMA COLUNA
SELECT * FROM TB_TURMA

UPDATE TB_TURMA
SET ID_PERIODO = 104,
   ID_STATUS = 0

-- ATUALIZANDO COLUNAS COM DADOS DE OUTRA COLUNA
UPDATE TB_TURMA
SET DT_TERMINO = DATEADD(DAY,45,DT_INICIO)

-- EXCLUINDO DADOS DA TABELA
SELECT * FROM TB_CURSO

DELETE FROM TB_CURSO  --FROM É OPCIONAL
WHERE NM_TITULO = 'ACADEMIA MARKETDATA'

DELETE FROM TB_CURSO --FROM É OPCIONAL

INSERT INTO TB_CURSO VALUES ('EXCEL','É LEGAL',40)

TRUNCATE TABLE TB_CURSO