-- Formas de comentar o código
-- Criando a primeira tabela
/*Criando a primeira tabela*/

CREATE TABLE TB_CURSO --NOME DE OBJETO COMEÇA COM LETRA, DEPOIS PODE TER LETRA, NÚMERO E ANDERLINE(_)
(
	ID_CURSO          INT, 
	NM_TITULO         VARCHAR(20),
	DS_CURSO          VARCHAR(8000),
	VL_CARGA_HORARIA  INT
);

--ALTERANDO UMA COLUNA
ALTER TABLE TB_CURSO
ALTER COLUMN NM_TITULO VARCHAR(40)

--ALTERANDO TABELA INCLUINDO COLUNAS
ALTER TABLE TB_CURSO
ADD VL_CURSO DECIMAL(6,2)

--ALTERANDO UMA TABELA EXCLUINDO COLUNA
ALTER TABLE TB_CURSO
DROP COLUMN VL_CURSO2

--EXCLUINDO UMA TABELA
DROP TABLE TB_CURSO

--RENOMEAR TABELA
SP_RENAME 'TB_CURSO', 'TB_CURSO2'

--RENOMEAR COLUNA
SP_RENAME 'TB_CURSO.VL_CURSO', 'VL_CURSO2', 'COLUMN' 