-- TABELA TEMPORÁRIA LOCAL
SELECT GETDATE() AS DT_HR_SISTEMA
	INTO #TESTE

SELECT * FROM #TESTE

-- TABELA TEMPORÁRIA GLOBAL
SELECT GETDATE() AS DT_HR_SISTEMA
	INTO ##TESTE

SELECT * FROM ##TESTE


-- VARIÁVEL DO TIPO TABELA
declare @TESTE TABLE (DT_HR_SISTEMA DATETIME)

insert @teste select getdate()

select * from @TESTE

-- Dos clientes que compraram, 
--qual foi o que mais gastou e o que menos gastou em 2020?

declare @mais_gastou  table(id_cliente int, nm_cliente varchar(200), vl_comprado decimal(9,2))
declare @menos_gastou table(id_cliente int, nm_cliente varchar(200), vl_comprado decimal(9,2))

insert @mais_gastou 
SELECT TOP 1
	TB_CLIENTE.ID_CLIENTE,
	TB_CLIENTE.NM_CLIENTE,
	SUM(VL_SUBTOTAL + VL_FRETE) AS TOTAL_COMPRADO
FROM TB_CLIENTE
	INNER JOIN TB_VENDA ON TB_CLIENTE.ID_CLIENTE = TB_VENDA.ID_CLIENTE
WHERE TB_VENDA.DT_VENDA BETWEEN '20200101' AND '20201231 23:59:59'
GROUP BY TB_CLIENTE.ID_CLIENTE,TB_CLIENTE.NM_CLIENTE
ORDER BY TOTAL_COMPRADO DESC -- MAIS COMPROU

insert @menos_gastou 
SELECT TOP 1
	TB_CLIENTE.ID_CLIENTE,
	TB_CLIENTE.NM_CLIENTE,
	SUM(VL_SUBTOTAL + VL_FRETE) AS TOTAL_COMPRADO
FROM TB_CLIENTE
	INNER JOIN TB_VENDA ON TB_CLIENTE.ID_CLIENTE = TB_VENDA.ID_CLIENTE
WHERE TB_VENDA.DT_VENDA BETWEEN '20200101' AND '20201231 23:59:59'
GROUP BY TB_CLIENTE.ID_CLIENTE,TB_CLIENTE.NM_CLIENTE
ORDER BY TOTAL_COMPRADO -- MENOS COMPROU

SELECT * FROM @mais_gastou
UNION
SELECT * FROM @menos_gastou

-- CTE
WITH TESTE (DT_HR_SISTEMA)
AS
( 
	SELECT GETDATE()
)
SELECT * FROM TESTE

-- Dos clientes que compraram, 
--qual foi o que mais gastou e o que menos gastou em 2020?
WITH 
mais_gastou (ID_CLIENTE, NM_CLIENTE, TOTAL_COMPRADO) AS
(
SELECT TOP 1
	TB_CLIENTE.ID_CLIENTE,
	TB_CLIENTE.NM_CLIENTE,
	SUM(VL_SUBTOTAL + VL_FRETE) AS TOTAL_COMPRADO
FROM TB_CLIENTE
	INNER JOIN TB_VENDA ON TB_CLIENTE.ID_CLIENTE = TB_VENDA.ID_CLIENTE
WHERE TB_VENDA.DT_VENDA BETWEEN '20200101' AND '20201231 23:59:59'
GROUP BY TB_CLIENTE.ID_CLIENTE,TB_CLIENTE.NM_CLIENTE
ORDER BY TOTAL_COMPRADO DESC -- MAIS COMPROU
),
MENOS_GASTOU (ID_CLIENTE, NM_CLIENTE, TOTAL_COMPRADO) AS
(
SELECT TOP 1
	TB_CLIENTE.ID_CLIENTE,
	TB_CLIENTE.NM_CLIENTE,
	SUM(VL_SUBTOTAL + VL_FRETE) AS TOTAL_COMPRADO
FROM TB_CLIENTE
	INNER JOIN TB_VENDA ON TB_CLIENTE.ID_CLIENTE = TB_VENDA.ID_CLIENTE
WHERE TB_VENDA.DT_VENDA BETWEEN '20200101' AND '20201231 23:59:59'
GROUP BY TB_CLIENTE.ID_CLIENTE,TB_CLIENTE.NM_CLIENTE
ORDER BY TOTAL_COMPRADO -- MENOS COMPROU
)
SELECT * FROM mais_gastou
UNION
SELECT * FROM menos_gastou
