USE DB_MADA_VAREJO 

/*
CRIE UMA VARIÁVEL DE TABELA @VENDA_MENSAL COM AS SEGUINTES COLUNAS:
ANO_VENDA
MES_VENDA
ESTADO_ENTREGA
VALOR_VENDA
*/
DECLARE @VENDA_MENSAL TABLE (ANO_VENDA INT, MES_VENDA INT, ESTADO_ENTREGA VARCHAR(50), VALOR_VENDA DECIMAL(9,2))

INSERT @VENDA_MENSAL 
SELECT
	YEAR(TB_VENDA.DT_VENDA)							ANO_VENDA,
	MONTH(TB_VENDA.DT_VENDA)						MES_VENDA,
	TB_ENDERECO.NM_ESTADO							ESTADO_ENTREGA,
	SUM(TB_VENDA.VL_SUBTOTAL + TB_VENDA.VL_FRETE)	VALOR_VENDA
FROM TB_VENDA
	INNER JOIN TB_ENDERECO
		ON TB_VENDA.ID_ENDERECOENTREGA = TB_ENDERECO.ID_ENDERECO
GROUP BY 
	YEAR(TB_VENDA.DT_VENDA)							
	,MONTH(TB_VENDA.DT_VENDA)						
	,TB_ENDERECO.NM_ESTADO							

SELECT * FROM @VENDA_MENSAL

--TENDO COMO BASE A VARIÁVEL TABELA @VENDA_MENSAL, 
--SELECIONE O MÊS COM MAIOR VALOR DE VENDA DE CADA ANO PARA CADA ESTADO.

DECLARE @VENDA_MENSAL_ESTADO_ANO TABLE (
	ANO_VENDA INT, 
	MES_VENDA INT, 
	ESTADO_ENTREGA VARCHAR(50), 
	VALOR_VENDA DECIMAL(9,2),
	MAIOR_VALOR_ANO_ESTADO DECIMAL (9,2),
	RANKING_MES	INT
)

INSERT @VENDA_MENSAL_ESTADO_ANO
SELECT 
	*,
	MAX(VALOR_VENDA) OVER (PARTITION BY ANO_VENDA, ESTADO_ENTREGA) AS MAIOR_VALOR_ANO_ESTADO,
	ROW_NUMBER() OVER (PARTITION BY ANO_VENDA, ESTADO_ENTREGA ORDER BY VALOR_VENDA DESC) AS RANKING_MES
FROM @VENDA_MENSAL
ORDER BY ESTADO_ENTREGA, ANO_VENDA, MES_VENDA

SELECT * FROM @VENDA_MENSAL_ESTADO_ANO
WHERE VALOR_VENDA = MAIOR_VALOR_ANO_ESTADO
ORDER BY ESTADO_ENTREGA, ANO_VENDA, MES_VENDA

SELECT * FROM @VENDA_MENSAL_ESTADO_ANO
WHERE RANKING_MES = 1
ORDER BY ESTADO_ENTREGA, ANO_VENDA, MES_VENDA


/*
CRIE UMA CTE VENDA_MENSAL COM AS SEGUINTES COLUNAS:
ANO_VENDA
MES_VENDA
ESTADO_ENTREGA
VALOR_VENDA
*/
WITH 
VENDA_MENSAL (ANO_VENDA , MES_VENDA , ESTADO_ENTREGA , VALOR_VENDA ) AS
(
SELECT
	YEAR(TB_VENDA.DT_VENDA)							ANO_VENDA,
	MONTH(TB_VENDA.DT_VENDA)						MES_VENDA,
	TB_ENDERECO.NM_ESTADO							ESTADO_ENTREGA,
	SUM(TB_VENDA.VL_SUBTOTAL + TB_VENDA.VL_FRETE)	VALOR_VENDA
FROM TB_VENDA
	INNER JOIN TB_ENDERECO
		ON TB_VENDA.ID_ENDERECOENTREGA = TB_ENDERECO.ID_ENDERECO
GROUP BY 
	YEAR(TB_VENDA.DT_VENDA)							
	,MONTH(TB_VENDA.DT_VENDA)						
	,TB_ENDERECO.NM_ESTADO							
)

SELECT * FROM VENDA_MENSAL
ORDER BY ESTADO_ENTREGA, ANO_VENDA, MES_VENDA

--TENDO COMO BASE A CTE VENDA_MENSAL, 
--SELECIONE O MÊS COM MAIOR VALOR DE VENDA DE CADA ANO PARA CADA ESTADO.

WITH 
VENDA_MENSAL (ANO_VENDA , MES_VENDA , ESTADO_ENTREGA , VALOR_VENDA ) AS
(
SELECT
	YEAR(TB_VENDA.DT_VENDA)							ANO_VENDA,
	MONTH(TB_VENDA.DT_VENDA)						MES_VENDA,
	TB_ENDERECO.NM_ESTADO							ESTADO_ENTREGA,
	SUM(TB_VENDA.VL_SUBTOTAL + TB_VENDA.VL_FRETE)	VALOR_VENDA
FROM TB_VENDA
	INNER JOIN TB_ENDERECO
		ON TB_VENDA.ID_ENDERECOENTREGA = TB_ENDERECO.ID_ENDERECO
GROUP BY 
	YEAR(TB_VENDA.DT_VENDA)							
	,MONTH(TB_VENDA.DT_VENDA)						
	,TB_ENDERECO.NM_ESTADO							
),
VENDA_MENSAL_ESTADO_ANO (ANO_VENDA,	MES_VENDA, 	ESTADO_ENTREGA,	VALOR_VENDA, MAIOR_VALOR_ANO_ESTADO, RANKING_MES) AS
(
 SELECT 
	*,
	MAX(VALOR_VENDA) OVER (PARTITION BY ANO_VENDA, ESTADO_ENTREGA) AS MAIOR_VALOR_ANO_ESTADO,
	ROW_NUMBER() OVER (PARTITION BY ANO_VENDA, ESTADO_ENTREGA ORDER BY VALOR_VENDA DESC) AS RANKING_MES
FROM VENDA_MENSAL
)
SELECT * FROM VENDA_MENSAL_ESTADO_ANO
WHERE VALOR_VENDA = MAIOR_VALOR_ANO_ESTADO
ORDER BY ESTADO_ENTREGA, ANO_VENDA, MES_VENDA

WITH 
VENDA_MENSAL (ANO_VENDA , MES_VENDA , ESTADO_ENTREGA , VALOR_VENDA ) AS
(
SELECT
	YEAR(TB_VENDA.DT_VENDA)							ANO_VENDA,
	MONTH(TB_VENDA.DT_VENDA)						MES_VENDA,
	TB_ENDERECO.NM_ESTADO							ESTADO_ENTREGA,
	SUM(TB_VENDA.VL_SUBTOTAL + TB_VENDA.VL_FRETE)	VALOR_VENDA
FROM TB_VENDA
	INNER JOIN TB_ENDERECO
		ON TB_VENDA.ID_ENDERECOENTREGA = TB_ENDERECO.ID_ENDERECO
GROUP BY 
	YEAR(TB_VENDA.DT_VENDA)							
	,MONTH(TB_VENDA.DT_VENDA)						
	,TB_ENDERECO.NM_ESTADO							
),
VENDA_MENSAL_ESTADO_ANO (ANO_VENDA,	MES_VENDA, 	ESTADO_ENTREGA,	VALOR_VENDA, MAIOR_VALOR_ANO_ESTADO, RANKING_MES) AS
(
 SELECT 
	*,
	MAX(VALOR_VENDA) OVER (PARTITION BY ANO_VENDA, ESTADO_ENTREGA) AS MAIOR_VALOR_ANO_ESTADO,
	ROW_NUMBER() OVER (PARTITION BY ANO_VENDA, ESTADO_ENTREGA ORDER BY VALOR_VENDA DESC) AS RANKING_MES
FROM VENDA_MENSAL
)
SELECT * FROM VENDA_MENSAL_ESTADO_ANO
WHERE RANKING_MES = 1
ORDER BY ESTADO_ENTREGA, ANO_VENDA, MES_VENDA