--MÃO NA MASSA INDIVIDUAL VARIÁVEL TABELA/ CTE
--COLOQUE O BANCO O DB_MADA_VAREJO EM USO 
USE DB_MADA_VAREJO 


--1. CRIE UMA VARIÁVEL TABELA/ CTE "VENDA_MENSAL" COM AS SEGUINTES COLUNAS:
--ANO_VENDA
--MES_VENDA
--ESTADO_ENTREGA
--VALOR_VENDA

-- VARIÁVEL DO TIPO TABELA
DECLARE @VENDA_MENSAL TABLE(VL_ANO_VENDA INT, VL_MES_VENDA INT, NM_ESTADO_ENTREGA VARCHAR(50), VL_VALOR_VENDA DECIMAL(9,2))
INSERT @VENDA_MENSAL
SELECT
	YEAR(TB_VENDA.DT_VENDA) ANO_VENDA,
	MONTH(TB_VENDA.DT_VENDA) MES_VENDA,
	TB_ENDERECO.NM_ESTADO	ESTADO_ENTREGA,
	SUM(TB_VENDA.VL_SUBTOTAL + TB_VENDA.VL_FRETE) VALOR_VENDA
FROM TB_VENDA
	INNER JOIN TB_ENDERECO
		ON TB_VENDA.ID_ENDERECOENTREGA = TB_ENDERECO.ID_ENDERECO
GROUP BY 
	YEAR(TB_VENDA.DT_VENDA),							
	MONTH(TB_VENDA.DT_VENDA),						
	TB_ENDERECO.NM_ESTADO	

SELECT * FROM @VENDA_MENSAL

--COM CTE
WITH
VENDA_MENSAL (VL_ANO_VENDA, VL_MES_VENDA, NM_ESTADO_ENTREGA, VL_VALOR_VENDA) AS
(
SELECT
	YEAR(TB_VENDA.DT_VENDA)							ANO_VENDA,
	MONTH(TB_VENDA.DT_VENDA)						MES_VENDA,
	TB_ENDERECO.NM_ESTADO							ESTADO_ENTREGA,
	SUM(TB_VENDA.VL_SUBTOTAL + TB_VENDA.VL_FRETE)	VALOR_VENDA
FROM TB_VENDA
	INNER JOIN TB_ENDERECO
		ON TB_VENDA.ID_ENDERECOENTREGA = TB_ENDERECO.ID_ENDERECO
GROUP BY 
	YEAR(TB_VENDA.DT_VENDA)							
	,MONTH(TB_VENDA.DT_VENDA)						
	,TB_ENDERECO.NM_ESTADO
)

SELECT * FROM VENDA_MENSAL


--2. TENDO COMO BASE A VARIÁVEL TABELA/ CTE "VENDA_MENSAL", 
--SELECIONE O MÊS COM MAIOR VALOR DE VENDA DE CADA ANO PARA CADA ESTADO.

-- COM VARIÁVEL DO TIPO TABELA
SELECT 
	*,
	MAX(VALOR_VENDA) OVER (PARTITION BY ANO_VENDA, ESTADO_ENTREGA) AS MAIOR_VALOR_ANO_ESTADO,
	ROW_NUMBER() OVER (PARTITION BY ANO_VENDA, ESTADO_ENTREGA ORDER BY VALOR_VENDA DESC) AS RANKING_MES
FROM @VENDA_MENSAL
ORDER BY ESTADO_ENTREGA, ANO_VENDA, MES_VENDA

SELECT * FROM @VENDA_MENSAL
WHERE VALOR_VENDA = MAIOR_VALOR_ANO_ESTADO
ORDER BY ESTADO_ENTREGA, ANO_VENDA, MES_VENDA

SELECT * FROM @VENDA_MENSAL
WHERE RANKING_MES = 1
ORDER BY ESTADO_ENTREGA, ANO_VENDA, MES_VENDA

--COM CTE
SELECT 
	*,
	MAX(VALOR_VENDA) OVER (PARTITION BY ANO_VENDA, ESTADO_ENTREGA) AS MAIOR_VALOR_ANO_ESTADO,
	ROW_NUMBER() OVER (PARTITION BY ANO_VENDA, ESTADO_ENTREGA ORDER BY VALOR_VENDA DESC) AS RANKING_MES
FROM VENDA_MENSAL
ORDER BY ESTADO_ENTREGA, ANO_VENDA, MES_VENDA

SELECT * FROM VENDA_MENSAL
WHERE VALOR_VENDA = MAIOR_VALOR_ANO_ESTADO
ORDER BY ESTADO_ENTREGA, ANO_VENDA, MES_VENDA

SELECT * FROM VENDA_MENSAL
WHERE RANKING_MES = 1
ORDER BY ESTADO_ENTREGA, ANO_VENDA, MES_VENDA

