-- quantas vendas realizamos
SELECT 
	COUNT(*)			AS QTD_REGISTROS,
	COUNT(DT_ENTREGA)	AS QTD_ENTREGA
FROM TB_VENDA

-- QUAL O PREÇO MÉDIO DE CUSTO , O MAIOR PREÇO DE CUSTO E O MENOR PREÇO DE CUSTO
SELECT 
	AVG(VL_PRECOCUSTO) AS MEDIA_CUSTO,
	MAX(VL_PRECOCUSTO) AS MAIOR_CUSTO,
	MIN(VL_PRECOCUSTO) AS MENOR_CUSTO
FROM TB_PRODUTO

-- TOTAL VENDIDO (r$)
SELECT
	SUM(VL_SUBTOTAL) AS TOTAL_VENDIDO
FROM TB_VENDA

-- QUANTO (r$) FOI VENDIDO DO PRODUTO "Chromebook Samsung XE310XBA-KT1BR Intel Celeron"
SELECT 
	SUM( QT_ITEM * (VL_PRECOUNITARIO - VL_DESCONTOUNITARIO) )
FROM TB_PRODUTO
	INNER JOIN TB_VENDAITEM 
		ON TB_PRODUTO.ID_PRODUTO = TB_VENDAITEM.ID_PRODUTO
WHERE NM_PRODUTO = 'Chromebook Samsung XE310XBA-KT1BR Intel Celeron'

-- TOTAL VENDIDO (r$) EM 2019
SELECT
	SUM(VL_SUBTOTAL) AS TOTAL_VENDIDO
FROM TB_VENDA
WHERE YEAR(DT_VENDA) = 2019

-- QTOS CLIENTES COMPRARAM EM MARÇO DE 2021
SELECT  
	COUNT(*)					QT_VENDAS,
	COUNT(ID_CLIENTE)			[QT_CLIENTE?],
	COUNT(DISTINCT ID_CLIENTE)	QT_CLIENTES_DISTINTOS,
	CAST(COUNT(*) AS DECIMAL(4,1)) /  
	COUNT(DISTINCT ID_CLIENTE)  AS FREQ_MEDIA --FREQ_MEDIA_DE_COMPRAS
FROM TB_VENDA
WHERE DT_VENDA BETWEEN '2021-03-01' AND '2021-03-31 23:59:59'

-- QUANTO (R$) FOI VENDIDO POR PRODUTO
SELECT
	NM_PRODUTO,
	SUM( QT_ITEM * (VL_PRECOUNITARIO - ISNULL(VL_DESCONTOUNITARIO, 0)) ) VALOR_TOTAL
FROM TB_PRODUTO
	INNER JOIN TB_VENDAITEM 
		ON TB_PRODUTO.ID_PRODUTO = TB_VENDAITEM.ID_PRODUTO
GROUP BY NM_PRODUTO

-- OS 10 PRODUTOS QUE MAIS VENDERAM EM (R$) e exibir também a quantidade vendida
SELECT TOP 10 
	NM_PRODUTO, 
	SUM( QT_ITEM * (VL_PRECOUNITARIO - ISNULL(VL_DESCONTOUNITARIO, 0)) ) as VLR_VENDIDO,
	SUM( QT_ITEM) as QTD_VENDIDA
FROM TB_PRODUTO
	INNER JOIN TB_VENDAITEM 
		ON TB_PRODUTO.ID_PRODUTO = TB_VENDAITEM.ID_PRODUTO
GROUP BY NM_PRODUTO
ORDER BY 2 DESC

-- TOTAL VENDIDO POR ANO
SELECT
	YEAR(DT_VENDA)		AS ANO_VENDA,
	SUM(VL_SUBTOTAL)	AS VL_VENDIDO,
	SUM(VL_SUBTOTAL)	
		/
	COUNT(DISTINCT(MONTH(DT_VENDA))) AS FAT_MEDIO_MES
FROM TB_VENDA
GROUP BY YEAR(DT_VENDA)
ORDER BY ANO_VENDA

-- TOTAL VENDIDO POR ANO SOMENTE O PRIMEIRO SEMESTRE 
SELECT
	YEAR(DT_VENDA)		AS ANO_VENDA,
	SUM(VL_SUBTOTAL)	AS VL_VENDIDO,
	SUM(VL_SUBTOTAL)	
		/
	COUNT(DISTINCT(MONTH(DT_VENDA))) AS FAT_MEDIO_MES
FROM TB_VENDA
WHERE MONTH(DT_VENDA) <= 6
-- MONTH(DT_VENDA) IN (1,2,3,4,5,6)
-- MONTH(DT_VENDA) BETWEEN 1 AND 6
GROUP BY YEAR(DT_VENDA)
ORDER BY ANO_VENDA

-- EXIBIR VENDAS POR ANO E TRIMESTRES 
SELECT	
	YEAR(DT_VENDA) AS ANO,
	DATEPART(QUARTER,DT_VENDA) AS TRI,
	SUM(VL_SUBTOTAL) AS TOT_VENDA
FROM TB_VENDA
GROUP BY YEAR(DT_VENDA) , DATEPART(QUARTER,DT_VENDA)
ORDER BY 1,2

-- EXIBIR VENDAS POR ANO E TRIMESTRES, SOMENTE TRIMESTRES 
--COM MAIS DE 5 MILHÕES EM VENDAS. 
SELECT	
	YEAR(DT_VENDA) AS ANO,
	DATEPART(QUARTER,DT_VENDA) AS TRI,
	SUM(VL_SUBTOTAL) AS TOT_VENDA
FROM TB_VENDA
GROUP BY YEAR(DT_VENDA) , DATEPART(QUARTER,DT_VENDA)
HAVING SUM(VL_SUBTOTAL) > 5000000
ORDER BY 1,2

-- EXIBIR VENDAS POR MÊS, SOMENTE DOS MESES COM 31 DIAS 
--COM MAIS DE 1 MILHÃO E 700 MIL EM VENDAS. 
SELECT	
	YEAR(DT_VENDA) AS ANO,
	MONTH(DT_VENDA) AS MES,
	SUM(VL_SUBTOTAL) AS TOT_VENDA
FROM TB_VENDA
WHERE MONTH(DT_VENDA) IN (1,3,5,7,8,10,12)
GROUP BY YEAR(DT_VENDA) , MONTH(DT_VENDA) 
HAVING SUM(VL_SUBTOTAL) > 1700000
ORDER BY 1,2