SELECT * FROM TB_PRODUTO
ORDER BY ID_CATEGORIA

SELECT * FROM TB_CATEGORIA
WHERE ID_CATEGORIA IN (25,18,76,17,57)


-- INNER JOIN  - INTERSEÇÃO DAS TABELAS
SELECT * 
	FROM TB_PRODUTO
	INNER JOIN TB_CATEGORIA 
	ON TB_PRODUTO.ID_CATEGORIA = TB_CATEGORIA.ID_CATEGORIA


SELECT 
	TB_PRODUTO.*,
	TB_CATEGORIA.NM_CATEGORIA
FROM TB_PRODUTO
	INNER JOIN TB_CATEGORIA 
	ON TB_PRODUTO.ID_CATEGORIA = TB_CATEGORIA.ID_CATEGORIA

SELECT
	TB_PRODUTO.NM_PRODUTO,
	TB_CATEGORIA.NM_CATEGORIA
FROM TB_PRODUTO
	INNER JOIN TB_CATEGORIA
	ON TB_PRODUTO.ID_CATEGORIA = TB_CATEGORIA.ID_CATEGORIA 

-- ERROS COMUNS
SELECT
	*
FROM TB_PRODUTO
	INNER JOIN TB_CATEGORIA
	ON TB_PRODUTO.ID_PRODUTO = TB_CATEGORIA.ID_CATEGORIA -- CRUZAMENTO ERRADO !!!!!

SELECT
	*
FROM TB_PRODUTO
	INNER JOIN TB_CATEGORIA
	ON TB_PRODUTO.ID_CATEGORIA = TB_PRODUTO.ID_CATEGORIA -- CRUZAMENTO ERRADO !!!!!
ORDER BY 1


-- INNER JOIN COM 3 TABELAS
SELECT
	TB_VENDA.DT_VENDA,
	TB_VENDAITEM.QT_ITEM,
	TB_PRODUTO.NM_PRODUTO
FROM TB_PRODUTO
	INNER JOIN TB_VENDAITEM 
		ON TB_PRODUTO.ID_PRODUTO = TB_VENDAITEM.ID_PRODUTO
	INNER JOIN TB_VENDA
		ON TB_VENDA.ID_VENDA = TB_VENDAITEM.ID_VENDA

	
-- PRODUTOS VENDIDOS EM MARÇO/19
SELECT DISTINCT 
	TB_PRODUTO.NM_PRODUTO
FROM TB_PRODUTO
	INNER JOIN TB_VENDAITEM 
		ON TB_PRODUTO.ID_PRODUTO = TB_VENDAITEM.ID_PRODUTO
	INNER JOIN TB_VENDA
		ON TB_VENDA.ID_VENDA = TB_VENDAITEM.ID_VENDA
WHERE TB_VENDA.DT_VENDA BETWEEN '20190301' AND '20190331 23:59:59'


SELECT DISTINCT 
	TB_PRODUTO.NM_PRODUTO
FROM TB_VENDA
	INNER JOIN TB_VENDAITEM 
		ON TB_VENDA.ID_VENDA = TB_VENDAITEM.ID_VENDA
	INNER JOIN TB_PRODUTO
		ON TB_VENDAITEM.ID_PRODUTO = TB_PRODUTO.ID_PRODUTO
WHERE TB_VENDA.DT_VENDA BETWEEN '20190301' AND '20190331 23:59:59'

-- INNER JOIN COM 3 TABELAS
SELECT
	V.DT_VENDA,
	VI.QT_ITEM,
	P.NM_PRODUTO
FROM TB_PRODUTO  P
	INNER JOIN TB_VENDAITEM  VI
		ON P.ID_PRODUTO = VI.ID_PRODUTO
	INNER JOIN TB_VENDA V
		ON V.ID_VENDA = VI.ID_VENDA

SELECT
	C.DT_VENDA,
	B.QT_ITEM,
	A.NM_PRODUTO
FROM TB_PRODUTO  A
	INNER JOIN TB_VENDAITEM  B
		ON A.ID_PRODUTO = B.ID_PRODUTO
	INNER JOIN TB_VENDA C
		ON B.ID_VENDA = C.ID_VENDA

-- LEFT OUTER JOIN - INTERSECÇÃO + TODOS REGISTROS DA TABELA DA "ESQUERDA" 

-- TODOS OS CLIENTES COM DADOS DE VENDA OU NÃO
SELECT 
	* 
FROM TB_CLIENTE	
	LEFT OUTER JOIN TB_VENDA 
		ON TB_CLIENTE.ID_CLIENTE = TB_VENDA.ID_CLIENTE
ORDER BY 1

-- TODOS OS CLIENTES QUE NUNCA COMPRARAM
SELECT 
	* 
FROM TB_CLIENTE	
	LEFT OUTER JOIN TB_VENDA 
		ON TB_CLIENTE.ID_CLIENTE = TB_VENDA.ID_CLIENTE
WHERE TB_VENDA.ID_CLIENTE IS NULL

-- NOME DO PRODUTO, NOME DA CATEGORIA E NOME DA CATEGORIA SUPERIOR
SELECT
	TB_PRODUTO.NM_PRODUTO,
	TB_CATEGORIA.NM_CATEGORIA,
	TB_CATEGORIA_SUPERIOR.NM_CATEGORIA AS NM_CATEGORIA_SUPERIOR
FROM TB_PRODUTO
	INNER JOIN TB_CATEGORIA 
		ON TB_PRODUTO.ID_CATEGORIA = TB_CATEGORIA.ID_CATEGORIA
	LEFT JOIN TB_CATEGORIA AS TB_CATEGORIA_SUPERIOR
		ON TB_CATEGORIA_SUPERIOR.ID_CATEGORIA = TB_CATEGORIA.ID_CATEGORIA_SUPERIOR

-- TODOS OS CLIENTES COM DADOS DE VENDA OU NÃO
SELECT 
	* 
FROM TB_VENDA 
	RIGHT OUTER JOIN TB_CLIENTE	
		ON TB_CLIENTE.ID_CLIENTE = TB_VENDA.ID_CLIENTE
ORDER BY 1

-- CLIENTES E SEUS RESPECTIVOS ENDEREÇOS, SE NÃO TIVER ENDERÇO EXIBA O CLIENTE
SELECT * FROM 
	TB_CLIENTE
	LEFT JOIN TB_ENDERECOCLIENTE
	 ON TB_CLIENTE.ID_CLIENTE = TB_ENDERECOCLIENTE.ID_CLIENTE
	LEFT JOIN TB_ENDERECO
	 ON TB_ENDERECO.ID_ENDERECO = TB_ENDERECOCLIENTE.ID_ENDERECO

-- ENDEREÇOES E SEUS RESPECTIVOS CLIENTES, SE NÃO TIVER CLIENTE EXIBA O ENDEREÇO
SELECT * FROM 
	TB_CLIENTE
	RIGHT JOIN TB_ENDERECOCLIENTE
	 ON TB_CLIENTE.ID_CLIENTE = TB_ENDERECOCLIENTE.ID_CLIENTE
	RIGHT JOIN TB_ENDERECO
	 ON TB_ENDERECO.ID_ENDERECO = TB_ENDERECOCLIENTE.ID_ENDERECO
ORDER BY TB_CLIENTE.ID_CLIENTE

-- TODOS ENDEREÇOES E SEUS RESPECTIVOS CLIENTES, E TODOS OS CLIENTE
SELECT * FROM 
	TB_CLIENTE
	FULL JOIN TB_ENDERECOCLIENTE
	 ON TB_CLIENTE.ID_CLIENTE = TB_ENDERECOCLIENTE.ID_CLIENTE
	FULL JOIN TB_ENDERECO
	 ON TB_ENDERECO.ID_ENDERECO = TB_ENDERECOCLIENTE.ID_ENDERECO
ORDER BY TB_CLIENTE.ID_CLIENTE

-- CLIENTES SEM ENDEREÇO OU ENDEREÇO SEM CLIENTE
SELECT * FROM 
	TB_CLIENTE
	FULL JOIN TB_ENDERECOCLIENTE
	 ON TB_CLIENTE.ID_CLIENTE = TB_ENDERECOCLIENTE.ID_CLIENTE
	FULL JOIN TB_ENDERECO
	 ON TB_ENDERECO.ID_ENDERECO = TB_ENDERECOCLIENTE.ID_ENDERECO
WHERE TB_ENDERECOCLIENTE.ID_ENDERECO IS NULL -- CLIENTE SEM ENDEREÇO
OR TB_ENDERECOCLIENTE.ID_CLIENTE IS NULL -- ENDEREÇO SEM CLIENTE
ORDER BY TB_CLIENTE.ID_CLIENTE


-- COMBINANDO TODOS OS PRODUTOS COM TODAS AS CATEGORIAS
SELECT * FROM 
	TB_PRODUTO CROSS JOIN TB_CATEGORIA