--Mão na massa individual

USE FABIANA

--CRIE UMA VIEW QUE RETORNE OS CLIENTES QUE RECEBEREAM SUAS 
--COMPRAS NOS ULTIMOS 30 DIAS

--VIEW
CREATE VIEW VW_COMPRAS_CLIENTES
AS
SELECT * FROM TB_CLIENTE
INNER JOIN TB_VENDA
	ON TB_CLIENTE. ID_CLIENTE = TB_VENDA.ID_CLIENTE
WHERE TB_VENDA.DT_ENTREGA  BETWEEN (GETDATE()-30) AND GETDATE()

SELECT DBO.VW_COMPRAS_CLIENTES FROM  DB_MADA_VAREJO..TB_CLIENTE 
 

--FUNCTION

CREATE FUNCTION FN_DATA_FORMATADA(@DATA DATETIME)
RETURNS VARCHAR(80)
AS
BEGIN
	DECLARE @DATA_OK VARCHAR(80)
	SET  @DATA_OK =
	CONCAT(DAY(@DATA),
	CASE (MONTH(@DATA)) 
		WHEN 1	THEN ' de janeiro de '
		WHEN 2	THEN ' de fevereiro de '
		WHEN 3	THEN ' de março de '
		WHEN 4	THEN ' de abril de '
		WHEN 5	THEN ' de maio de '
		WHEN 6	THEN ' de junho de '
		WHEN 7	THEN ' de julho de '
		WHEN 8	THEN ' de agosto de '
		WHEN 9	THEN ' de setembro de '
		WHEN 10	THEN ' de outubro de '
		WHEN 11	THEN ' de novembro de '
		WHEN 12	THEN ' de dezembro de '
	END, YEAR(@DATA))

	RETURN (@DATA_OK)
END

SELECT DBO.FN_DATA_FORMATADA(DT_VENDA) 
FROM DB_MADA_VAREJO..TB_VENDA


