20210629_20210628_SELECT_BASICO_2

-- TODOS ENDEREÇOS DE SÃO PAULO
SELECT * FROM TB_ENDERECO
WHERE NM_CIDADE = 'SÃO PAULO'

-- TODOS OS CLIENTES QUE CHAMEM GUSTAVO
SELECT * FROM TB_CLIENTE
WHERE NM_CLIENTE = 'GUSTAVO'

SELECT * FROM TB_CLIENTE
WHERE NM_CLIENTE LIKE 'GUSTAVO%' -- % "substitui" qualquer qtd de caracteres

-- TODOS OS CLIENTES QUE CHAMEM MARIA
SELECT * FROM TB_CLIENTE
WHERE NM_CLIENTE LIKE 'MARIA%'

SELECT * FROM TB_CLIENTE
WHERE NM_CLIENTE LIKE 'MARIA %'

-- TODOS OS CLIENTES QUE TERMINEM COM SANTOS
SELECT * FROM TB_CLIENTE
WHERE NM_CLIENTE LIKE '%SANTOS'

--TODOS CLIENTE QUE CONTENHAM SANTOS NO NOME (QUALQUER PARTE)
SELECT * FROM TB_CLIENTE
WHERE NM_CLIENTE LIKE '%SANTOS%'
ORDER BY NM_CLIENTE

--TODOS CLIENTE QUE CONTENHAM SANTOS NO NOME (SOMENTE NO MEIO)
SELECT * FROM TB_CLIENTE
WHERE NM_CLIENTE LIKE '% SANTOS %'
ORDER BY NM_CLIENTE

-- CLIENTES QUE TERMINEM COM FERREIRA OU PEREIRA
SELECT * FROM TB_CLIENTE
WHERE NM_CLIENTE LIKE '%ferreira' OR
NM_CLIENTE LIKE '%pereira'

-- CATEGORIAS COM A SEGUNDA LETRA "A"
SELECT * FROM TB_CATEGORIA
WHERE NM_CATEGORIA LIKE '_A%' -- O "_" substitui um único caracter

-- Terceiro e quarto caracteres do código postal seja "45"
SELECT * FROM TB_ENDERECO
WHERE CD_CODIGOPOSTAL LIKE '__45%'

-- CLIENTES QUE CHAMEM "MARIA" OU "MARIO"
SELECT * FROM TB_CLIENTE
WHERE NM_CLIENTE LIKE 'MARI[AO] %'

-- CLIENTES QUE CHAMEM "JOSE" OU "JOSÉ"
SELECT * FROM TB_CLIENTE
WHERE NM_CLIENTE LIKE 'JOS[EÉ] %'

-- NOMES QUE COMECEM COM VOGAL
SELECT * FROM TB_CLIENTE
WHERE NM_CLIENTE LIKE '[AEIOU]%'

-- NOMES QUE COMECEM CONSOANTE
SELECT * FROM TB_CLIENTE
WHERE NM_CLIENTE NOT LIKE '[AEIOU]%'

-- EMAIL SEM @
SELECT * FROM TB_CLIENTE
WHERE DS_EMAIL NOT LIKE '%@%.%'

-- TODOS OS ITENS COM DESCONTO MAIOR QUE 50
SELECT * FROM TB_VENDAITEM -- 806 LINHAS
WHERE VL_DESCONTOUNITARIO > 50
ORDER BY VL_DESCONTOUNITARIO 

-- TUDO EXCETO OS ITENS COM DESCONTO MAIOR QUE 50
SELECT * FROM TB_VENDAITEM -- 940 LINHAS  
WHERE VL_DESCONTOUNITARIO <= 50
ORDER BY VL_DESCONTOUNITARIO 

-- TODOS OS ITENS COM DESCONTO
SELECT * FROM TB_VENDAITEM
WHERE VL_DESCONTOUNITARIO IS NOT NULL

-- TODOS OS ITENS SEM DESCONTO
SELECT * FROM TB_VENDAITEM
WHERE VL_DESCONTOUNITARIO IS NULL

-- FUNÇÕES QUE TRATAM O NULL ISNULL / COALESCE
SELECT *, ISNULL(VL_DESCONTOUNITARIO,0) DESCONTO_TRATADO 
FROM TB_VENDAITEM

-- TUDO EXCETO OS ITENS COM DESCONTO MAIOR QUE 50
SELECT *,  ISNULL(VL_DESCONTOUNITARIO,0) FROM TB_VENDAITEM -- 15.652 LINHAS  
WHERE ISNULL(VL_DESCONTOUNITARIO,0) <= 50
ORDER BY VL_DESCONTOUNITARIO 

-- DATA DE REFERENCIA 
-- EXIBIR A DATA DE ENTREGA, SE NÃO TIVER, EXIBIR DATA DE ENVIO, SE NÃO TIVER 
-- EXIBIR DATA DE VENDA

SELECT
	*,
	COALESCE(DT_ENTREGA,DT_ENVIO,DT_VENDA) AS DT_REFERENCIA
FROM TB_VENDA
ORDER BY DT_VENDA
